
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Luban;


namespace ET
{
public partial class EquipmentConfigCategory
{
    public EquipmentConfigCategory()
    {
        _dataList = new System.Collections.Generic.List<ET.EquipmentConfig>()
        {
            new ET.EquipmentConfig(10004, 1),
            new ET.EquipmentConfig(10005, 2),
            new ET.EquipmentConfig(10006, 3),
            new ET.EquipmentConfig(10007, 3),
            new ET.EquipmentConfig(10008, 4),
            new ET.EquipmentConfig(10009, 5),
            new ET.EquipmentConfig(10010, 1),
            new ET.EquipmentConfig(10011, 7),
            new ET.EquipmentConfig(10012, 8)
        };
        _dataMap = new System.Collections.Generic.Dictionary<int, ET.EquipmentConfig>(_dataList.Count);
        foreach (var _v in _dataList)
        {
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }
}
}
