
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Luban;


namespace ET
{
public sealed class EquipmentConfigCategoryFactory : IConfigFactory
{
    public System.Type ConfigType => typeof(EquipmentConfigCategory);

    public ASingleton Create()
    {
        return new EquipmentConfigCategory(new System.Collections.Generic.List<ET.EquipmentConfig>()
        {
            new ET.EquipmentConfig(10004, 1),
            new ET.EquipmentConfig(10005, 2),
            new ET.EquipmentConfig(10006, 3),
            new ET.EquipmentConfig(10007, 3),
            new ET.EquipmentConfig(10008, 4),
            new ET.EquipmentConfig(10009, 5),
            new ET.EquipmentConfig(10010, 1),
            new ET.EquipmentConfig(10011, 7),
            new ET.EquipmentConfig(10012, 8)
        });
    }
}
}
