
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Luban;


namespace ET
{
public sealed class MapConfigCategoryFactory : IConfigFactory
{
    public System.Type ConfigType => typeof(MapConfigCategory);

    public ASingleton Create()
    {
        return new MapConfigCategory(new System.Collections.Generic.List<ET.MapConfig>()
        {
            new ET.MapConfig(1, @"GateMap", @"GateMap", ET.CopyType.Normal, @""),
            new ET.MapConfig(2, @"Map1", @"Map1", ET.CopyType.Normal, @"Map1"),
            new ET.MapConfig(3, @"Map2", @"Map2", ET.CopyType.Line, @"Map1"),
            new ET.MapConfig(4, @"Lordaeron", @"Lordaeron", ET.CopyType.Copy, @"Lordaeron")
        });
    }
}
}
