
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Luban;


namespace ET
{
public partial class NumericTypeConfigCategory
{
    public NumericTypeConfigCategory()
    {
        _dataList = new System.Collections.Generic.List<ET.NumericTypeConfig>()
        {
            new ET.NumericTypeConfig(1000, @"Speed", 0, new System.Collections.Generic.Dictionary<int, long> { }),
            new ET.NumericTypeConfig(1001, @"HP", 1002, new System.Collections.Generic.Dictionary<int, long> { }),
            new ET.NumericTypeConfig(1002, @"MaxHP", 0, new System.Collections.Generic.Dictionary<int, long> { }),
            new ET.NumericTypeConfig(1003, @"MP", 1004, new System.Collections.Generic.Dictionary<int, long> { }),
            new ET.NumericTypeConfig(1004, @"MaxMP", 0, new System.Collections.Generic.Dictionary<int, long> { }),
            new ET.NumericTypeConfig(1005, @"Radius", 0, new System.Collections.Generic.Dictionary<int, long> { }),
            new ET.NumericTypeConfig(1006, @"AOI", 0, new System.Collections.Generic.Dictionary<int, long> { }),
            new ET.NumericTypeConfig(1007, @"Height", 0, new System.Collections.Generic.Dictionary<int, long> { }),
            new ET.NumericTypeConfig(1008, @"Weight", 0, new System.Collections.Generic.Dictionary<int, long> { }),
            new ET.NumericTypeConfig(1009, @"AI", 0, new System.Collections.Generic.Dictionary<int, long> { }),
            new ET.NumericTypeConfig(1010, @"X", 0, new System.Collections.Generic.Dictionary<int, long> { }),
            new ET.NumericTypeConfig(1011, @"Y", 0, new System.Collections.Generic.Dictionary<int, long> { }),
            new ET.NumericTypeConfig(1012, @"Z", 0, new System.Collections.Generic.Dictionary<int, long> { }),
            new ET.NumericTypeConfig(1013, @"Stun", 0, new System.Collections.Generic.Dictionary<int, long> { }),
            new ET.NumericTypeConfig(1014, @"Yaw", 0, new System.Collections.Generic.Dictionary<int, long> { }),
            new ET.NumericTypeConfig(1015, @"Phase", 0, new System.Collections.Generic.Dictionary<int, long> { })
        };
        _dataMap = new System.Collections.Generic.Dictionary<int, ET.NumericTypeConfig>(_dataList.Count);
        foreach (var _v in _dataList)
        {
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }
}
}
