
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Luban;


namespace ET
{
public partial class QuestConfigCategory
{
    public QuestConfigCategory()
    {
        _dataList = new System.Collections.Generic.List<ET.QuestConfig>()
        {
            new ET.QuestConfig(1, @"烦人的野猪", @"击杀3只野猪", new int[] { 1 }, new int[] { }, new int[] { 2 }, @"烦人的野猪", @"野猪骚扰老百姓，请帮忙清除！", @"麻烦您了！", @"谢谢您帮我清除了野猪！", 10024, @"Map2", 10024, @"Map2"),
            new ET.QuestConfig(2, @"暴躁的熊", @"击杀1头熊", new int[] { 2 }, new int[] { }, new int[] { }, @"暴躁的熊", @"附近出现了一头熊，很危险！", @"麻烦您了！", @"谢谢！", 10024, @"Map2", 10024, @"Map2")
        };
        _dataMap = new System.Collections.Generic.Dictionary<int, ET.QuestConfig>(_dataList.Count);
        foreach (var _v in _dataList)
        {
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }
}
}
