
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Luban;


namespace ET
{
public sealed class UnitConfigCategoryFactory : IConfigFactory
{
    public System.Type ConfigType => typeof(UnitConfigCategory);

    public ASingleton Create()
    {
        return new UnitConfigCategory(new System.Collections.Generic.List<ET.UnitConfig>()
        {
            new ET.UnitConfig(1001, ET.UnitType.Player, @"Mage", @"Portrait", ET.EClassType.Mage),
            new ET.UnitConfig(1002, ET.UnitType.Virtual, @"TrainingDummy", @"UI-ChatIcon-Battlenet", ET.EClassType.DeathKnight),
            new ET.UnitConfig(1003, ET.UnitType.Monster, @"Boar", @"UI-ChatIcon-Battlenet", ET.EClassType.Druid),
            new ET.UnitConfig(1004, ET.UnitType.Monster, @"Bear", @"UI-ChatIcon-Battlenet", ET.EClassType.Priest),
            new ET.UnitConfig(1005, ET.UnitType.NPC, @"Mage", @"UI-ChatIcon-Battlenet", ET.EClassType.Warrior)
        });
    }
}
}
