
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET.YIUITest
{

    [Config]
    public partial class YIUIItemConfigCategory : Singleton<YIUIItemConfigCategory>, ILubanConfig
    {
        private readonly Dictionary<int, YIUITest.YIUIItemConfig> _dataMap;
        private readonly List<YIUITest.YIUIItemConfig> _dataList;
        
        public YIUIItemConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, YIUITest.YIUIItemConfig>();
            _dataList = new List<YIUITest.YIUIItemConfig>();
            
            for(int n = _buf.ReadSize() ; n > 0 ; --n)
            {
                YIUITest.YIUIItemConfig _v;
                _v = YIUITest.YIUIItemConfig.DeserializeYIUIItemConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }
            EndInit();
        }

        public Dictionary<int, YIUITest.YIUIItemConfig> GetAll() => _dataMap;
        public Dictionary<int, YIUITest.YIUIItemConfig> DataMap => _dataMap;
        public List<YIUITest.YIUIItemConfig> DataList => _dataList;

        public YIUITest.YIUIItemConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);

        public YIUITest.YIUIItemConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            LubanLog.Error(this,key);
            return default;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
            EndRef();
        }


        partial void EndRef();
    }

}

