
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ET
{
    public sealed partial class MapConfig : ET.Object
    {
        public MapConfig(int Id, string Name, string Desc, ET.CopyType CopyType, int MaxLineNum, int MaxPlayerNum, int RecommendPlayerNum, string MapResName) 
        {
            this.Id = Id;
            this.Name = Name;
            this.Desc = Desc;
            this.CopyType = CopyType;
            this.MaxLineNum = MaxLineNum;
            this.MaxPlayerNum = MaxPlayerNum;
            this.RecommendPlayerNum = RecommendPlayerNum;
            this.MapResName = MapResName;
            EndInit();
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 地图名字
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// 描述
        /// </summary>
        public readonly string Desc;
        /// <summary>
        /// 副本类型
        /// </summary>
        public readonly ET.CopyType CopyType;
        /// <summary>
        /// 最大分线数量
        /// </summary>
        public readonly int MaxLineNum;
        /// <summary>
        /// 单线最大人数
        /// </summary>
        public readonly int MaxPlayerNum;
        /// <summary>
        /// 推荐人数，超过开新线
        /// </summary>
        public readonly int RecommendPlayerNum;
        /// <summary>
        /// 地图场景资源
        /// </summary>
        public readonly string MapResName;

        public  void ResolveRef()
        {
            EndRef();
        }

        partial void EndInit();
        partial void EndRef();
    }

}

