
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ET
{
    [EnableClass]
    public sealed partial class MapTransferRuleConfig
    {
        public MapTransferRuleConfig(int Id, string ToMap, float[] Pos) 
        {
            this.Id = Id;
            this.ToMap = ToMap;
            this.Pos = Pos;
            EndInit();
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 目标地图
        /// </summary>
        public readonly string ToMap;
        /// <summary>
        /// 目标位置
        /// </summary>
        public readonly float[] Pos;

        public  void ResolveRef()
        {
            EndRef();
        }

        partial void EndInit();
        partial void EndRef();
    }

}

