
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ET
{
    public sealed partial class QuestObjectiveParams_CollectItem : ET.QuestObjectiveParams
    {
        public QuestObjectiveParams_CollectItem(int ItemId)  : base()
        {
            this.ItemId = ItemId;
            EndInit();
        }

        /// <summary>
        /// 道具Id
        /// </summary>
        public readonly int ItemId;

        public override void ResolveRef()
        {
            base.ResolveRef();
            EndRef();
        }

        partial void EndInit();
        partial void EndRef();
    }

}

