
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ET
{
    [EnableClass]
    public sealed partial class UnitConfig
    {
        public UnitConfig(int Id, ET.UnitType UnitType, string Name, ET.EClassType ClassType, System.Collections.Generic.Dictionary<NumericType, long> KV) 
        {
            this.Id = Id;
            this.UnitType = UnitType;
            this.Name = Name;
            this.ClassType = ClassType;
            this.KV = KV;
            EndInit();
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// Type
        /// </summary>
        public readonly ET.UnitType UnitType;
        /// <summary>
        /// 名字
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// 职业
        /// </summary>
        public readonly ET.EClassType ClassType;
        /// <summary>
        /// 速度Base
        /// </summary>
        public readonly System.Collections.Generic.Dictionary<NumericType, long> KV;

        public  void ResolveRef()
        {
            EndRef();
        }

        partial void EndInit();
        partial void EndRef();
    }

}

