
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ET
{
    [EnableClass]
    public sealed partial class ConditionExpr
    {
        public ConditionExpr(string Expr, int ErrorCode, string Desc) 
        {
            this.Expr = Expr;
            this.ErrorCode = ErrorCode;
            this.Desc = Desc;
            EndInit();
        }

        /// <summary>
        /// 条件表达式
        /// </summary>
        public readonly string Expr;
        /// <summary>
        /// 表达式节点未填写错误码时使用
        /// </summary>
        public readonly int ErrorCode;
        /// <summary>
        /// 策划备注
        /// </summary>
        public readonly string Desc;

        public  void ResolveRef()
        {
            EndRef();
        }

        partial void EndInit();
        partial void EndRef();
    }

}

