
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ET
{
    public sealed partial class EquipmentConfig : ET.Object
    {
        public EquipmentConfig(int Id, int EquipSlot) 
        {
            this.Id = Id;
            this.EquipSlot = EquipSlot;
            EndInit();
        }

        /// <summary>
        /// ID
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 装备部位
        /// </summary>
        public readonly int EquipSlot;

        public  void ResolveRef()
        {
            EndRef();
        }

        partial void EndInit();
        partial void EndRef();
    }

}

