
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ET
{
[ConfigProcess(ConfigType.Code)]
public partial class MapTransferRuleConfigCategory : Singleton<MapTransferRuleConfigCategory>, IConfig
{
    private readonly System.Collections.Generic.Dictionary<int, ET.MapTransferRuleConfig> _dataMap;

    public MapTransferRuleConfigCategory(System.Collections.Generic.Dictionary<int, ET.MapTransferRuleConfig> dataMap)
    {
        _dataMap = dataMap;
        EndInit();
    }

    public System.Collections.Generic.Dictionary<int, ET.MapTransferRuleConfig> GetAll() => _dataMap;
    public System.Collections.Generic.IReadOnlyDictionary<int, ET.MapTransferRuleConfig> DataMap => _dataMap;
    public ET.MapTransferRuleConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public ET.MapTransferRuleConfig Get(int key) => _dataMap[key];
    public ET.MapTransferRuleConfig this[int key] => _dataMap[key];

    public void ResolveRef()
    {
        foreach (var _v in _dataMap.Values)
        {
            _v.ResolveRef();
        }
        EndRef();
    }

    partial void EndRef();
}
}

