
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ET
{
    public sealed partial class QuestObjectiveConfig : ET.Object
    {
        public QuestObjectiveConfig(int Id, string Name, string Desc, ET.QuestObjectiveType Type, int NeedCount, ET.QuestObjectiveParams Params) 
        {
            this.Id = Id;
            this.Name = Name;
            this.Desc = Desc;
            this.Type = Type;
            this.NeedCount = NeedCount;
            this.Params = Params;
            EndInit();
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 任务目标名字
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// 任务描述
        /// </summary>
        public readonly string Desc;
        /// <summary>
        /// 任务类型
        /// </summary>
        public readonly ET.QuestObjectiveType Type;
        /// <summary>
        /// 需要的数量
        /// </summary>
        public readonly int NeedCount;
        /// <summary>
        /// 任务目标参数
        /// </summary>
        public readonly ET.QuestObjectiveParams Params;

        public  void ResolveRef()
        {
            Params?.ResolveRef();
            EndRef();
        }

        partial void EndInit();
        partial void EndRef();
    }

}

