
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ET
{
    public sealed partial class TextConfig : ET.Object
    {
        public TextConfig(int Id, string Name, string CN, string EN) 
        {
            this.Id = Id;
            this.Name = Name;
            this.CN = CN;
            this.EN = EN;
            EndInit();
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 名字
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// 中文
        /// </summary>
        public readonly string CN;
        /// <summary>
        /// 英文
        /// </summary>
        public readonly string EN;

        public  void ResolveRef()
        {
            EndRef();
        }

        partial void EndInit();
        partial void EndRef();
    }

}

