
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{

    [Config]
    public partial class TextConfigCategory : Singleton<TextConfigCategory>, ILubanConfig
    {
        private readonly Dictionary<int, TextConfig> _dataMap;
        private readonly List<TextConfig> _dataList;
        
        public TextConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, TextConfig>();
            _dataList = new List<TextConfig>();
            
            for(int n = _buf.ReadSize() ; n > 0 ; --n)
            {
                TextConfig _v;
                _v = TextConfig.DeserializeTextConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }
            EndInit();
        }

        public Dictionary<int, TextConfig> GetAll() => _dataMap;
        public Dictionary<int, TextConfig> DataMap => _dataMap;
        public List<TextConfig> DataList => _dataList;

        public TextConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);

        public TextConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            LubanLog.Error(this,key);
            return default;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
            EndRef();
        }


        partial void EndRef();
    }

}

