
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class UnitConfig : Luban.BeanBase
    {
        public UnitConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            Type = _buf.ReadInt();
            Name = _buf.ReadString();
            HeadIcon = _buf.ReadString();
            ClassType = (EClassType)_buf.ReadInt();

            EndInit();
        }

        public static UnitConfig DeserializeUnitConfig(ByteBuf _buf)
        {
            return new UnitConfig(_buf);
        }

        public readonly int Id;
        public readonly int Type;
        public readonly string Name;
        public readonly string HeadIcon;
        public readonly EClassType ClassType;
    
        public const int __ID__ = -568528378;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Type:" + Type + ","
            + "Name:" + Name + ","
            + "headIcon:" + HeadIcon + ","
            + "classType:" + ClassType + ","
            + "}";
        }

        partial void EndRef();
    }

}

