
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class QuestObjectiveConfig : Luban.BeanBase
    {
        public QuestObjectiveConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            Desc = _buf.ReadString();
            Type = (ET.QuestObjectiveType)_buf.ReadInt();
            NeedCount = _buf.ReadInt();

            EndInit();
        }

        public static QuestObjectiveConfig DeserializeQuestObjectiveConfig(ByteBuf _buf)
        {
            return new ET.QuestObjectiveConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 任务目标名字
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// 任务描述
        /// </summary>
        public readonly string Desc;
        /// <summary>
        /// 任务类型
        /// </summary>
        public readonly ET.QuestObjectiveType Type;
        /// <summary>
        /// 需要的数量
        /// </summary>
        public readonly int NeedCount;
    
        public const int __ID__ = -70847336;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "Desc:" + Desc + ","
            + "Type:" + Type + ","
            + "NeedCount:" + NeedCount + ","
            + "}";
        }

        partial void EndRef();
    }

}

