
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public abstract partial class QuestObjectiveParams : Luban.BeanBase
    {
        public QuestObjectiveParams(ByteBuf _buf) 
        {

            EndInit();
        }

        public static QuestObjectiveParams DeserializeQuestObjectiveParams(ByteBuf _buf)
        {
            switch (_buf.ReadInt())
            {
                case ET.QuestObjectiveParams_KillMonster.__ID__: return new ET.QuestObjectiveParams_KillMonster(_buf);
                case ET.QuestObjectiveParams_Collectltem.__ID__: return new ET.QuestObjectiveParams_Collectltem(_buf);
                default: throw new SerializationException();
            }
        }

    

        public virtual void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "}";
        }

        partial void EndRef();
    }

}

