
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{

    [ConfigProcess]
    public partial class MapTransferRuleConfigCategory : Singleton<MapTransferRuleConfigCategory>, IConfig
    {
        private readonly Dictionary<int, MapTransferRuleConfig> _dataMap;
        private readonly List<MapTransferRuleConfig> _dataList;
        
        public MapTransferRuleConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, MapTransferRuleConfig>();
            _dataList = new List<MapTransferRuleConfig>();
            
            for(int n = _buf.ReadSize() ; n > 0 ; --n)
            {
                MapTransferRuleConfig _v;
                _v = global::ET.MapTransferRuleConfig.DeserializeMapTransferRuleConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }
            EndInit();
        }

        public Dictionary<int, MapTransferRuleConfig> GetAll() => _dataMap;
        public Dictionary<int, MapTransferRuleConfig> DataMap => _dataMap;
        public List<MapTransferRuleConfig> DataList => _dataList;

        public MapTransferRuleConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);

        public MapTransferRuleConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            LubanLog.Error(this,key);
            return default;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
            EndRef();
        }


        partial void EndRef();
    }

}

