
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class UnitConfig : Luban.BeanBase
    {
        public UnitConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            UnitType = (UnitType)_buf.ReadInt();
            Name = _buf.ReadString();
            MapName = _buf.ReadString();
            HeadIcon = _buf.ReadString();
            ClassType = (EClassType)_buf.ReadInt();
            {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);KV = new System.Collections.Generic.Dictionary<int, long>(n0 * 3 / 2);for(var i0 = 0 ; i0 < n0 ; i0++) { int _k0;  _k0 = _buf.ReadInt(); long _v0;  _v0 = _buf.ReadLong();     KV.Add(_k0, _v0);}}

            EndInit();
        }

        public static UnitConfig DeserializeUnitConfig(ByteBuf _buf)
        {
            return new UnitConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// Type
        /// </summary>
        public readonly UnitType UnitType;
        /// <summary>
        /// 名字
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// 所在地图
        /// </summary>
        public readonly string MapName;
        /// <summary>
        /// 头像图片
        /// </summary>
        public readonly string HeadIcon;
        /// <summary>
        /// 职业
        /// </summary>
        public readonly EClassType ClassType;
        /// <summary>
        /// 出生X坐标
        /// </summary>
        public readonly System.Collections.Generic.Dictionary<int, long> KV;
    
        public const int __ID__ = -568528378;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "UnitType:" + UnitType + ","
            + "Name:" + Name + ","
            + "MapName:" + MapName + ","
            + "headIcon:" + HeadIcon + ","
            + "classType:" + ClassType + ","
            + "KV:" + Luban.StringUtil.CollectionToString(KV) + ","
            + "}";
        }

        partial void EndRef();
    }

}

