
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Luban;


namespace ET.Server
{
[ConfigGroup("Moba")]
public sealed class StartSceneConfigCategoryFactory_Moba : IConfigFactory
{
    public System.Type ConfigType => typeof(StartSceneConfigCategory);

    public ASingleton Create()
    {
        return new StartSceneConfigCategory(new System.Collections.Generic.Dictionary<int, ET.Server.StartSceneConfig>()
        {
            [ 1 ] = new ET.Server.StartSceneConfig(1, 1, 1, @"ServiceDiscovery", @"ServiceDiscovery", 0),
            [ 2 ] = new ET.Server.StartSceneConfig(2, 2, 1, @"RouterManager", @"RouterManager", 10101),
            [ 3 ] = new ET.Server.StartSceneConfig(3, 3, 1, @"Router", @"Router", 0),
            [ 1003 ] = new ET.Server.StartSceneConfig(1003, 1003, 1, @"Realm", @"Realm", 0),
            [ 1004 ] = new ET.Server.StartSceneConfig(1004, 1004, 1, @"Gate", @"Gate", 0),
            [ 2004 ] = new ET.Server.StartSceneConfig(2004, 2004, 1, @"Location", @"Location", 0),
            [ 2005 ] = new ET.Server.StartSceneConfig(2005, 2005, 1, @"Match", @"Match", 0),
            [ 3005 ] = new ET.Server.StartSceneConfig(3005, 3005, 1, @"MapManager", @"MapManager", 0)
        });
    }
}
}
