
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{ 
    [System.Flags]
    public enum UnitType
    {
        /// <summary>
        /// 玩家
        /// </summary>
        Player = 1,
        /// <summary>
        /// 怪物
        /// </summary>
        Monster = 2,
        /// <summary>
        /// 非玩家角色
        /// </summary>
        NPC = 4,
        /// <summary>
        /// 宠物
        /// </summary>
        Pet = 8,
    }

} 

