
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{ 
    public enum TransferType
    {
        /// <summary>
        /// 登录传送
        /// </summary>
        Login = 1,
        /// <summary>
        /// 普通传送
        /// </summary>
        Normal = 2,
        /// <summary>
        /// 分线传送
        /// </summary>
        Line = 3,
    }

} 

