
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
[ConfigGroup("Config")]
public sealed class ItemConfigCategoryFactory_Config : IConfigFactory
{
    public System.Type ConfigType => typeof(ItemConfigCategory);

    public ASingleton Create()
    {
        return new ItemConfigCategory(new System.Collections.Generic.Dictionary<int, ET.ItemConfig>()
        {
            [ 10001 ] = new ET.ItemConfig(10001, @"生命药水", 2, 99, 1, 1, 1),
            [ 10002 ] = new ET.ItemConfig(10002, @"魔法药水", 2, 99, 1, 1, 1),
            [ 10003 ] = new ET.ItemConfig(10003, @"铁矿石", 3, 999, 0, 0, 1),
            [ 10004 ] = new ET.ItemConfig(10004, @"新手之剑", 4, 1, 0, 2, 1),
            [ 10005 ] = new ET.ItemConfig(10005, @"皮革头盔", 4, 1, 0, 2, 1),
            [ 10006 ] = new ET.ItemConfig(10006, @"铁制胸甲", 4, 1, 1, 2, 5),
            [ 10007 ] = new ET.ItemConfig(10007, @"布袍", 4, 1, 0, 2, 1),
            [ 10008 ] = new ET.ItemConfig(10008, @"皮革护腿", 4, 1, 0, 2, 3),
            [ 10009 ] = new ET.ItemConfig(10009, @"铁靴", 4, 1, 1, 2, 5),
            [ 10010 ] = new ET.ItemConfig(10010, @"精灵之弓", 4, 1, 1, 2, 5),
            [ 10011 ] = new ET.ItemConfig(10011, @"魔法项链", 4, 1, 2, 2, 10),
            [ 10012 ] = new ET.ItemConfig(10012, @"力量戒指", 4, 1, 1, 2, 8)
        });
    }
}
}
