
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Luban;


namespace ET
{
[ConfigGroup("Config")]
public sealed class MapTransferRuleConfigCategoryFactory_Config : IConfigFactory
{
    public System.Type ConfigType => typeof(MapTransferRuleConfigCategory);

    public ASingleton Create()
    {
        return new MapTransferRuleConfigCategory(new System.Collections.Generic.Dictionary<int, ET.MapTransferRuleConfig>()
        {
            [ 1 ] = new ET.MapTransferRuleConfig(1, @"Map2", new float[] { }),
            [ 2 ] = new ET.MapTransferRuleConfig(2, @"Map1", new float[] { }),
            [ 3 ] = new ET.MapTransferRuleConfig(3, @"Lordaeron", new float[] { })
        });
    }
}
}
