
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Luban;


namespace ET
{
public sealed class QuestObjectiveConfigCategoryFactory : IConfigFactory
{
    public System.Type ConfigType => typeof(QuestObjectiveConfigCategory);

    public ASingleton Create()
    {
        return new QuestObjectiveConfigCategory(new System.Collections.Generic.Dictionary<int, ET.QuestObjectiveConfig>()
        {
            [ 1 ] = new ET.QuestObjectiveConfig(1, @"击杀3只野猪", @"击杀3只野猪", ET.QuestObjectiveType.KillMonster, 3, new ET.QuestObjectiveParams_KillMonster(1003)),
            [ 2 ] = new ET.QuestObjectiveConfig(2, @"击杀1头熊", @"击杀1头熊", ET.QuestObjectiveType.KillMonster, 1, new ET.QuestObjectiveParams_KillMonster(1004))
        });
    }
}
}
