
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
[ConfigGroup("Config")]
public sealed class TextConfigCategoryFactory_Config : IConfigFactory
{
    public System.Type ConfigType => typeof(TextConfigCategory);

    public ASingleton Create()
    {
        return new TextConfigCategory(new System.Collections.Generic.Dictionary<int, ET.TextConfig>()
        {
            [ 38001 ] = new ET.TextConfig(38001, @"Quest_NotAvailable", @"任务无效", @""),
            [ 38002 ] = new ET.TextConfig(38002, @"Quest_AlreadyAccepted", @"任务已接", @""),
            [ 38003 ] = new ET.TextConfig(38003, @"Quest_ComponentNotFound", @"任务组件不存在", @""),
            [ 38004 ] = new ET.TextConfig(38004, @"Quest_NotFound", @"任务没找到", @""),
            [ 38005 ] = new ET.TextConfig(38005, @"Quest_NotFoundNPC", @"没有找到NPC", @""),
            [ 38006 ] = new ET.TextConfig(38006, @"Quest_NPCTooFar", @"NPC太远了", @""),
            [ 38007 ] = new ET.TextConfig(38007, @"Quest_NotFinish", @"任务没有完成", @""),
            [ 37000 ] = new ET.TextConfig(37000, @"SpellCast_DistanceNotEnought", @"技能施放距离不够！", @"技能施放距离不够"),
            [ 37001 ] = new ET.TextConfig(37001, @"SpellCast_NotSelectTarget", @"没有选择目标！", @""),
            [ 37002 ] = new ET.TextConfig(37002, @"SpellCast_TargetTooFar", @"目标距离太远！", @""),
            [ 37003 ] = new ET.TextConfig(37003, @"SpellCast_SpellInCD", @"技能在冷却中！", @""),
            [ 37004 ] = new ET.TextConfig(37004, @"SpellCast_MPNotEnought", @"魔法值不足！", @""),
            [ 37005 ] = new ET.TextConfig(37005, @"SpellCast_HPNotEnought", @"生命值不足！", @""),
            [ 37006 ] = new ET.TextConfig(37006, @"SpellCast_TargetNotInFrontOfCaster", @"目标不在前方！", @"")
        });
    }
}
}
