
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

 
    public enum PhaseType
    {
        Normal = 1,
        Phase1 = 2,
        Phase2 = 4,
    }

 

