
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

 
    /// <summary>
    /// Numeric Type
    /// </summary>
    public enum NumericType
    {
        Speed = 1000,
        SpeedBase = 10001,
        SpeedAdd = 10002,
        SpeedPct = 10003,
        SpeedFinalAdd = 10004,
        SpeedFinalPct = 10005,
        HP = 1001,
        MaxHP = 1002,
        MaxHPBase = 10021,
        MaxHPAdd = 10022,
        MaxHPPct = 10023,
        MaxHPFinalAdd = 10024,
        MaxHPFinalPct = 10025,
        MP = 1003,
        MaxMP = 1004,
        MaxMPBase = 10041,
        MaxMPAdd = 10042,
        MaxMPPct = 10043,
        MaxMPFinalAdd = 10044,
        MaxMPFinalPct = 10045,
        Radius = 1005,
        RadiusBase = 10051,
        RadiusAdd = 10052,
        RadiusPct = 10053,
        RadiusFinalAdd = 10054,
        RadiusFinalPct = 10055,
        AOI = 1006,
        AOIBase = 10061,
        AOIAdd = 10062,
        AOIPct = 10063,
        AOIFinalAdd = 10064,
        AOIFinalPct = 10065,
        Height = 1007,
        HeightBase = 10071,
        HeightAdd = 10072,
        HeightPct = 10073,
        HeightFinalAdd = 10074,
        HeightFinalPct = 10075,
        Weight = 1008,
        WeightBase = 10081,
        WeightAdd = 10082,
        WeightPct = 10083,
        WeightFinalAdd = 10084,
        WeightFinalPct = 10085,
        AI = 1009,
        /// <summary>
        /// 出生X坐标
        /// </summary>
        X = 1010,
        /// <summary>
        /// 出生Y坐标
        /// </summary>
        Y = 1011,
        /// <summary>
        /// 出生Z坐标
        /// </summary>
        Z = 1012,
        /// <summary>
        /// 眩晕
        /// </summary>
        Stun = 1013,
        StunBase = 10131,
        StunAdd = 10132,
        StunPct = 10133,
        StunFinalAdd = 10134,
        StunFinalPct = 10135,
        /// <summary>
        /// 出生朝向
        /// </summary>
        Yaw = 1014,
        /// <summary>
        /// 相位
        /// </summary>
        Phase = 1015,
    }

 

