//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ET
{
    [ConfigGroup("Config")]
    public sealed class SpellConfigCategoryFactory_Config : IConfigFactory
    {
        public System.Type ConfigType => typeof(global::ET.SpellConfigCategory);

        public ASingleton Create()
        {
            global::ET.SpellConfigCategory category = new global::ET.SpellConfigCategory();
            category.Add(new global::ET.SpellConfig()
            {
                Id = 100000,
                Desc = @"普通攻击",
                IconName = @"Ability_Warrior_OffensiveStance",
                CD = 2000,
                DamageMultiplier = 0,
                Cost = null,
                TargetSelector = new global::ET.TargetSelectorSingle()
            {
                    Id = 1,
                    Children = new global::System.Collections.Generic.List<global::ET.BTNode>(),
                    TreeId = 7631256944332478928L,
                    Buff = @"Buff",
                    Caster = @"Caster",
                    Owner = @"Owner",
                    MaxDistance = 5000,
                    MinDistance = 0,
                    Unit = @"Unit",
                    UnitType = (global::ET.UnitType)7,
                },
            });
            category.Add(new global::ET.SpellConfig()
            {
                Id = 100001,
                Desc = @"普通攻击子技能",
                IconName = null,
                CD = 0,
                DamageMultiplier = 0,
                Cost = null,
                TargetSelector = new global::ET.TargetSelectorSingle()
            {
                    Id = 1,
                    Children = new global::System.Collections.Generic.List<global::ET.BTNode>(),
                    TreeId = 1947671076390841174L,
                    Buff = @"Buff",
                    Caster = @"Caster",
                    Owner = @"Owner",
                    MaxDistance = 5000,
                    MinDistance = 0,
                    Unit = @"Unit",
                    UnitType = (global::ET.UnitType)7,
                },
            });
            category.Add(new global::ET.SpellConfig()
            {
                Id = 100002,
                Desc = @"普通攻击子技能的子技能，用来伤害技能",
                IconName = null,
                CD = 0,
                DamageMultiplier = 0,
                Cost = null,
                TargetSelector = new global::ET.TargetSelectorSingle()
            {
                    Id = 1,
                    Children = new global::System.Collections.Generic.List<global::ET.BTNode>(),
                    TreeId = 7677868458425395227L,
                    Buff = @"Buff",
                    Caster = @"Caster",
                    Owner = @"Owner",
                    MaxDistance = 5000,
                    MinDistance = 0,
                    Unit = @"Unit",
                    UnitType = (global::ET.UnitType)7,
                },
            });
            category.Add(new global::ET.SpellConfig()
            {
                Id = 100010,
                Desc = @"暴风雪",
                IconName = @"Spell_Frost_IceStorm",
                CD = 5000,
                DamageMultiplier = 0,
                Cost = new global::ET.CostNode()
            {
                    Id = 1,
                    Children = new global::System.Collections.Generic.List<global::ET.BTNode>(),
                    TreeId = 546798687428771539L,
                    Buff = @"Buff",
                    Unit = @"Unit",
                    Check = @"Check",
                },
                TargetSelector = new global::ET.TargetSelectorPosition()
            {
                    Id = 1,
                    Children = new global::System.Collections.Generic.List<global::ET.BTNode>(),
                    TreeId = 8532739274120753170L,
                    Buff = @"Buff",
                    Caster = @"Caster",
                    Owner = @"Owner",
                    MaxDistance = 40000,
                    MinDistance = 0,
                    Pos = @"Pos",
                    Radius = 6000,
                    SpellIndicatorName = @"RoundIndicator",
                },
            });
            category.Add(new global::ET.SpellConfig()
            {
                Id = 100011,
                Desc = @"暴风雪每波雪技能",
                IconName = null,
                CD = 0,
                DamageMultiplier = 0,
                Cost = new global::ET.CostNode()
            {
                    Id = 1,
                    Children = new global::System.Collections.Generic.List<global::ET.BTNode>(),
                    TreeId = 6880836831554164778L,
                    Buff = @"Buff",
                    Unit = @"Unit",
                    Check = @"Check",
                },
                TargetSelector = new global::ET.TargetSelectorCircle()
            {
                    Id = 1,
                    Children = new global::System.Collections.Generic.List<global::ET.BTNode>(),
                    TreeId = 3603828126334052096L,
                    Buff = @"Buff",
                    Caster = @"Caster",
                    Owner = @"Owner",
                    MaxDistance = 40000,
                    MinDistance = 0,
                    Unit = @"Unit",
                    Units = @"Units",
                    Radius = 6000,
                    UnitType = (global::ET.UnitType)15,
                    SpellIndicatorName = @"RoundIndicator",
                },
            });
            category.Add(new global::ET.SpellConfig()
            {
                Id = 100020,
                Desc = @"寒冰箭",
                IconName = @"Spell_Frost_FrostBolt02",
                CD = 5000,
                DamageMultiplier = 0,
                Cost = new global::ET.CostNode()
            {
                    Id = 1,
                    Children = new global::System.Collections.Generic.List<global::ET.BTNode>(),
                    TreeId = 5765865364704420295L,
                    Buff = @"Buff",
                    Unit = @"Unit",
                    Check = @"Check",
                },
                TargetSelector = new global::ET.TargetSelectorSingle()
            {
                    Id = 1,
                    Children = new global::System.Collections.Generic.List<global::ET.BTNode>(),
                    TreeId = 8522967870078740376L,
                    Buff = @"Buff",
                    Caster = @"Caster",
                    Owner = @"Owner",
                    MaxDistance = 40000,
                    MinDistance = 0,
                    Unit = @"Unit",
                    UnitType = (global::ET.UnitType)15,
                },
            });
            category.Add(new global::ET.SpellConfig()
            {
                Id = 100030,
                Desc = @"捕获宠物",
                IconName = @"Spell_Druid_stampedingroar_cat",
                CD = 5000,
                DamageMultiplier = 0,
                Cost = null,
                TargetSelector = new global::ET.TargetSelectorSingle()
            {
                    Id = 1,
                    Children = new global::System.Collections.Generic.List<global::ET.BTNode>(),
                    TreeId = 8471560973426708924L,
                    Buff = @"Buff",
                    Caster = @"Caster",
                    Owner = @"Owner",
                    MaxDistance = 10000,
                    MinDistance = 0,
                    Unit = @"Unit",
                    UnitType = global::ET.UnitType.Monster,
                },
            });
            category.Add(new global::ET.SpellConfig()
            {
                Id = 100040,
                Desc = null,
                IconName = @"Ability_Druid_BalanceofPower",
                CD = 0,
                DamageMultiplier = 0,
                Cost = null,
                TargetSelector = new global::ET.TargetSelectorCaster()
            {
                    Id = 1,
                    Children = new global::System.Collections.Generic.List<global::ET.BTNode>(),
                    TreeId = 563801883277983586L,
                    Buff = @"Buff",
                    Caster = @"Caster",
                    Owner = @"Owner",
                    MaxDistance = 0,
                    MinDistance = 0,
                },
            });
            category.Add(new global::ET.SpellConfig()
            {
                Id = 100050,
                Desc = null,
                IconName = @"Ability_Druid_Bash",
                CD = 0,
                DamageMultiplier = 0,
                Cost = null,
                TargetSelector = new global::ET.TargetSelectorCaster()
            {
                    Id = 1,
                    Children = new global::System.Collections.Generic.List<global::ET.BTNode>(),
                    TreeId = 2667142274251165071L,
                    Buff = @"Buff",
                    Caster = @"Caster",
                    Owner = @"Owner",
                    MaxDistance = 0,
                    MinDistance = 0,
                },
            });
            category.Add(new global::ET.SpellConfig()
            {
                Id = 100100,
                Desc = @"怪物普通攻击",
                IconName = @"Ability_Druid_Berserk",
                CD = 2000,
                DamageMultiplier = 0,
                Cost = null,
                TargetSelector = new global::ET.TargetSelectorSingle()
            {
                    Id = 1,
                    Children = new global::System.Collections.Generic.List<global::ET.BTNode>(),
                    TreeId = 6695103805080215819L,
                    Buff = @"Buff",
                    Caster = @"Caster",
                    Owner = @"Owner",
                    MaxDistance = 3000,
                    MinDistance = 0,
                    Unit = @"Unit",
                    UnitType = (global::ET.UnitType)15,
                },
            });
            category.Add(new global::ET.SpellConfig()
            {
                Id = 100101,
                Desc = @"怪物普通攻击子技能",
                IconName = null,
                CD = 0,
                DamageMultiplier = 0,
                Cost = null,
                TargetSelector = new global::ET.TargetSelectorSingle()
            {
                    Id = 1,
                    Children = new global::System.Collections.Generic.List<global::ET.BTNode>(),
                    TreeId = 6058943084369442959L,
                    Buff = @"Buff",
                    Caster = @"Caster",
                    Owner = @"Owner",
                    MaxDistance = 3000,
                    MinDistance = 0,
                    Unit = @"Unit",
                    UnitType = (global::ET.UnitType)15,
                },
            });
            category.Add(new global::ET.SpellConfig()
            {
                Id = 100102,
                Desc = @"普通攻击子技能的子技能，用来伤害技能",
                IconName = null,
                CD = 0,
                DamageMultiplier = 0,
                Cost = null,
                TargetSelector = new global::ET.TargetSelectorSingle()
            {
                    Id = 1,
                    Children = new global::System.Collections.Generic.List<global::ET.BTNode>(),
                    TreeId = 7736548613039498410L,
                    Buff = @"Buff",
                    Caster = @"Caster",
                    Owner = @"Owner",
                    MaxDistance = 5000,
                    MinDistance = 0,
                    Unit = @"Unit",
                    UnitType = (global::ET.UnitType)15,
                },
            });
            category.Add(new global::ET.SpellConfig()
            {
                Id = 100110,
                Desc = @"怪物战斗状态",
                IconName = @"ABILITY_DRUID_DEMORALIZINGROAR",
                CD = 0,
                DamageMultiplier = 0,
                Cost = null,
                TargetSelector = new global::ET.TargetSelectorCaster()
            {
                    Id = 1,
                    Children = new global::System.Collections.Generic.List<global::ET.BTNode>(),
                    TreeId = 8152665677468152840L,
                    Buff = @"Buff",
                    Caster = @"Caster",
                    Owner = @"Owner",
                    MaxDistance = 0,
                    MinDistance = 0,
                },
            });
            category.Add(new global::ET.SpellConfig()
            {
                Id = 100120,
                Desc = null,
                IconName = null,
                CD = 0,
                DamageMultiplier = 0,
                Cost = null,
                TargetSelector = new global::ET.TargetSelectorRectangle()
            {
                    Id = 1,
                    Children = new global::System.Collections.Generic.List<global::ET.BTNode>(),
                    TreeId = 8481233880388386357L,
                    Buff = @"Buff",
                    Caster = @"Caster",
                    Owner = @"Owner",
                    MaxDistance = 10000,
                    MinDistance = 0,
                    SpellIndicatorName = null,
                    Width = 1000f,
                    Length = 100f,
                    UnitType = global::ET.UnitType.Player,
                },
            });
            category.Add(new global::ET.SpellConfig()
            {
                Id = 100130,
                Desc = null,
                IconName = null,
                CD = 0,
                DamageMultiplier = 0,
                Cost = null,
                TargetSelector = new global::ET.TargetSelectorRectangle()
            {
                    Id = 1,
                    Children = new global::System.Collections.Generic.List<global::ET.BTNode>(),
                    TreeId = 3090607549754946190L,
                    Buff = @"Buff",
                    Caster = @"Caster",
                    Owner = @"Owner",
                    MaxDistance = 10000,
                    MinDistance = 0,
                    SpellIndicatorName = null,
                    Width = 1000f,
                    Length = 100f,
                    UnitType = global::ET.UnitType.Player,
                },
            });
            return category;
        }
    }
}
