
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class NumericTypeConfig : Luban.BeanBase
    {
        public NumericTypeConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            NeedSaveDB = _buf.ReadInt();
            NoticeType = _buf.ReadInt();
            MaxNumericType = _buf.ReadInt();
            {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);AffectNumericType = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); AffectNumericType.Add(_e0);}}
            {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);AffectValue = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); AffectValue.Add(_e0);}}

            EndInit();
        }

        public static NumericTypeConfig DeserializeNumericTypeConfig(ByteBuf _buf)
        {
            return new NumericTypeConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 名字
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// 是否存数据库
        /// </summary>
        public readonly int NeedSaveDB;
        /// <summary>
        /// 广播给客户端类型
        /// </summary>
        public readonly int NoticeType;
        /// <summary>
        /// 对应的最大值属性
        /// </summary>
        public readonly int MaxNumericType;
        /// <summary>
        /// 影响的属性id
        /// </summary>
        public readonly System.Collections.Generic.List<int> AffectNumericType;
        /// <summary>
        /// 影响的属性数值
        /// </summary>
        public readonly System.Collections.Generic.List<int> AffectValue;
    
        public const int __ID__ = 57587177;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "NeedSaveDB:" + NeedSaveDB + ","
            + "NoticeType:" + NoticeType + ","
            + "MaxNumericType:" + MaxNumericType + ","
            + "AffectNumericType:" + Luban.StringUtil.CollectionToString(AffectNumericType) + ","
            + "AffectValue:" + Luban.StringUtil.CollectionToString(AffectValue) + ","
            + "}";
        }

        partial void EndRef();
    }

}

