
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{ 
    public enum EClassType
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 死亡骑士
        /// </summary>
        DeathKnight = 1,
        /// <summary>
        /// 恶魔猎手
        /// </summary>
        DemonHunter = 2,
        /// <summary>
        /// 德鲁伊
        /// </summary>
        Druid = 3,
        /// <summary>
        /// 猎人
        /// </summary>
        Hunter = 4,
        /// <summary>
        /// 法师
        /// </summary>
        Mage = 5,
        /// <summary>
        /// 武僧
        /// </summary>
        Monk = 6,
        /// <summary>
        /// 圣骑士
        /// </summary>
        Paladin = 7,
        /// <summary>
        /// 牧师
        /// </summary>
        Priest = 8,
        /// <summary>
        /// 盗贼
        /// </summary>
        Rogue = 9,
        /// <summary>
        /// 萨满
        /// </summary>
        Shaman = 10,
        /// <summary>
        /// 术士
        /// </summary>
        Warlock = 11,
        /// <summary>
        /// 战士
        /// </summary>
        Warrior = 12,
    }

} 

