
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class EquipmentConfig : Luban.BeanBase
    {
        public EquipmentConfig(int Id, int EquipSlot, System.Collections.Generic.Dictionary<int, long> KV) 
        {
            this.Id = Id;
            this.EquipSlot = EquipSlot;
            this.KV = KV;
            EndInit();
        }

        /// <summary>
        /// ID
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 装备部位
        /// </summary>
        public readonly int EquipSlot;
        /// <summary>
        /// 速度Base
        /// </summary>
        public readonly System.Collections.Generic.Dictionary<int, long> KV;

        public const int __ID__ = -904342767;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "id:" + Id + ","
            + "EquipSlot:" + EquipSlot + ","
            + "KV:" + Luban.StringUtil.CollectionToString(KV) + ","
            + "}";
        }

        partial void EndRef();
    }

}

