
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{ 
    public enum ItemType
    {
        Normal = 1,
        Equipment = 2,
        Consumable = 3,
        Material = 4,
        Quest = 5,
    }

} 

