
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ET
{
    [EnableClass]
    public sealed partial class ItemConfig : Luban.BeanBase
    {
        public ItemConfig(JSONNode _buf) 
        {
            { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
            { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
            { if(!_buf["Desc"].IsString) { throw new SerializationException(); }  Desc = _buf["Desc"]; }
            { if(!_buf["Type"].IsNumber) { throw new SerializationException(); }  Type = _buf["Type"]; }
            { if(!_buf["MaxStack"].IsNumber) { throw new SerializationException(); }  MaxStack = _buf["MaxStack"]; }
            { if(!_buf["Icon"].IsString) { throw new SerializationException(); }  Icon = _buf["Icon"]; }
            { if(!_buf["Quality"].IsNumber) { throw new SerializationException(); }  Quality = _buf["Quality"]; }
            { if(!_buf["UseType"].IsNumber) { throw new SerializationException(); }  UseType = _buf["UseType"]; }
            { if(!_buf["Level"].IsNumber) { throw new SerializationException(); }  Level = _buf["Level"]; }

            EndInit();
        }

        public static ItemConfig DeserializeItemConfig(JSONNode _buf)
        {
            return new ET.ItemConfig(_buf);
        }

        /// <summary>
        /// ID
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 名称
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// 描述
        /// </summary>
        public readonly string Desc;
        /// <summary>
        /// 类型
        /// </summary>
        public readonly int Type;
        /// <summary>
        /// 最大堆叠
        /// </summary>
        public readonly int MaxStack;
        /// <summary>
        /// 图标
        /// </summary>
        public readonly string Icon;
        /// <summary>
        /// 品质
        /// </summary>
        public readonly int Quality;
        /// <summary>
        /// 使用类型
        /// </summary>
        public readonly int UseType;
        /// <summary>
        /// 等级
        /// </summary>
        public readonly int Level;

        public const int __ID__ = 1663635188;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "Desc:" + Desc + ","
            + "Type:" + Type + ","
            + "MaxStack:" + MaxStack + ","
            + "Icon:" + Icon + ","
            + "Quality:" + Quality + ","
            + "UseType:" + UseType + ","
            + "Level:" + Level + ","
            + "}";
        }

        partial void EndRef();
    }

}

