
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ET
{
    [EnableClass]
    public sealed partial class MapUnitConfig
    {
        public MapUnitConfig(int Id, int UnitConfigId, string MapName, System.Collections.Generic.Dictionary<int, long> KV) 
        {
            this.Id = Id;
            this.UnitConfigId = UnitConfigId;
            this.MapName = MapName;
            this.KV = KV;
            EndInit();
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// UnitConfigId
        /// </summary>
        public readonly int UnitConfigId;
        /// <summary>
        /// 所在地图
        /// </summary>
        public readonly string MapName;
        /// <summary>
        /// 出生X坐标
        /// </summary>
        public readonly System.Collections.Generic.Dictionary<int, long> KV;

        public  void ResolveRef()
        {
            EndRef();
        }

        partial void EndInit();
        partial void EndRef();
    }

}

