
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class MapUnitConfig : Luban.BeanBase
    {
        public MapUnitConfig(int Id, int UnitConfigId, string MapName, System.Collections.Generic.Dictionary<int, long> KV) 
        {
            this.Id = Id;
            this.UnitConfigId = UnitConfigId;
            this.MapName = MapName;
            this.KV = KV;
            EndInit();
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// UnitConfigId
        /// </summary>
        public readonly int UnitConfigId;
        /// <summary>
        /// 所在地图
        /// </summary>
        public readonly string MapName;
        /// <summary>
        /// 出生X坐标
        /// </summary>
        public readonly System.Collections.Generic.Dictionary<int, long> KV;

        public const int __ID__ = -2012370621;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "UnitConfigId:" + UnitConfigId + ","
            + "MapName:" + MapName + ","
            + "KV:" + Luban.StringUtil.CollectionToString(KV) + ","
            + "}";
        }

        partial void EndRef();
    }

}

