
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class NumericTypeConfig : Luban.BeanBase
    {
        public NumericTypeConfig(int Id, string Name, int NeedSaveDB, NoticeType NoticeType, int MaxNumericType, System.Collections.Generic.Dictionary<int, long> AffectNumeric) 
        {
            this.Id = Id;
            this.Name = Name;
            this.NeedSaveDB = NeedSaveDB;
            this.NoticeType = NoticeType;
            this.MaxNumericType = MaxNumericType;
            this.AffectNumeric = AffectNumeric;
            EndInit();
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 名字
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// 是否存数据库
        /// </summary>
        public readonly int NeedSaveDB;
        /// <summary>
        /// 广播给客户端类型
        /// </summary>
        public readonly NoticeType NoticeType;
        /// <summary>
        /// 对应的最大值属性
        /// </summary>
        public readonly int MaxNumericType;
        /// <summary>
        /// 影响的属性id
        /// </summary>
        public readonly System.Collections.Generic.Dictionary<int, long> AffectNumeric;

        public const int __ID__ = 1076638314;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "NeedSaveDB:" + NeedSaveDB + ","
            + "NoticeType:" + NoticeType + ","
            + "MaxNumericType:" + MaxNumericType + ","
            + "AffectNumeric:" + Luban.StringUtil.CollectionToString(AffectNumeric) + ","
            + "}";
        }

        partial void EndRef();
    }

}

