
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class QuestObjectiveParams_CollectItem : ET.QuestObjectiveParams
    {
        public QuestObjectiveParams_CollectItem(int ItemId)  : base()
        {
            this.ItemId = ItemId;
            EndInit();
        }

        /// <summary>
        /// 道具Id
        /// </summary>
        public readonly int ItemId;

        public const int __ID__ = -1136348582;
        public override int GetTypeId() => __ID__;

        public override void ResolveRef(Tables tables)
        {
            base.ResolveRef(tables);
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "ItemId:" + ItemId + ","
            + "}";
        }

        partial void EndRef();
    }

}

