
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class QuestObjectiveConfig : Luban.BeanBase
    {
        public QuestObjectiveConfig(int Id, string Name, string Desc, ET.QuestObjectiveType Type, int NeedCount, ET.QuestObjectiveParams Params) 
        {
            this.Id = Id;
            this.Name = Name;
            this.Desc = Desc;
            this.Type = Type;
            this.NeedCount = NeedCount;
            this.Params = Params;
            EndInit();
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 任务目标名字
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// 任务描述
        /// </summary>
        public readonly string Desc;
        /// <summary>
        /// 任务类型
        /// </summary>
        public readonly ET.QuestObjectiveType Type;
        /// <summary>
        /// 需要的数量
        /// </summary>
        public readonly int NeedCount;
        /// <summary>
        /// 任务目标参数
        /// </summary>
        public readonly ET.QuestObjectiveParams Params;

        public const int __ID__ = -70847336;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(Tables tables)
        {
            Params?.ResolveRef(tables);
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "Desc:" + Desc + ","
            + "Type:" + Type + ","
            + "NeedCount:" + NeedCount + ","
            + "Params:" + Params + ","
            + "}";
        }

        partial void EndRef();
    }

}

