
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ET
{
    [EnableClass]
    public sealed partial class QuestObjectiveParams_KillMonster : ET.QuestObjectiveParams
    {
        public QuestObjectiveParams_KillMonster(int MonsterId)  : base()
        {
            this.MonsterId = MonsterId;
            EndInit();
        }

        /// <summary>
        /// 击杀的怪物Id
        /// </summary>
        public readonly int MonsterId;

        public override void ResolveRef()
        {
            base.ResolveRef();
            EndRef();
        }

        partial void EndInit();
        partial void EndRef();
    }

}

