
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ET
{
    [EnableClass]
    public sealed partial class TextConfig : Luban.BeanBase
    {
        public TextConfig(JSONNode _buf) 
        {
            { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
            { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
            { if(!_buf["CN"].IsString) { throw new SerializationException(); }  CN = _buf["CN"]; }
            { if(!_buf["EN"].IsString) { throw new SerializationException(); }  EN = _buf["EN"]; }

            EndInit();
        }

        public static TextConfig DeserializeTextConfig(JSONNode _buf)
        {
            return new ET.TextConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 名字
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// 中文
        /// </summary>
        public readonly string CN;
        /// <summary>
        /// 英文
        /// </summary>
        public readonly string EN;

        public const int __ID__ = 1515216270;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "CN:" + CN + ","
            + "EN:" + EN + ","
            + "}";
        }

        partial void EndRef();
    }

}

