using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using MongoDB.Bson.Serialization.Attributes;
using UnityEditor;
using UnityEngine;

namespace ET.Client
{
    public static class BTConfigCodeExporter
    {
        private const string AutoGeneratedHeader =
@"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------";

        private static readonly string[] HotfixConfigDirs =
        {
            "Packages/cn.etetet.excel/CodeMode/Config/Client/Config",
            "Packages/cn.etetet.excel/CodeMode/Config/ClientServer/Config",
            "Packages/cn.etetet.excel/CodeMode/Config/Server/Config",
        };

        private static readonly Dictionary<string, Type> RuntimeTypes = LoadRuntimeTypes();

        public static void Export(SpellConfigCategory spellConfigCategory, BuffConfigCategory buffConfigCategory)
        {
            string spellFactoryCode = GenerateFactoryCode(
                spellConfigCategory,
                "SpellConfigCategoryFactory",
                "SpellConfigCategory",
                spellConfigCategory.GetAll().Values.OrderBy(x => x.Id).Cast<object>().ToList());

            string buffFactoryCode = GenerateFactoryCode(
                buffConfigCategory,
                "BuffConfigCategoryFactory",
                "BuffConfigCategory",
                buffConfigCategory.GetAll().Values.OrderBy(x => x.Id).Cast<object>().ToList());

            foreach (string outputDir in HotfixConfigDirs)
            {
                Directory.CreateDirectory(outputDir);

                WriteAllTextIfChanged(Path.Combine(outputDir, "SpellConfigCategoryFactory.cs"), spellFactoryCode);
                WriteAllTextIfChanged(Path.Combine(outputDir, "BuffConfigCategoryFactory.cs"), buffFactoryCode);
            }

            AssetDatabase.Refresh();
        }

        private static string GenerateFactoryCode(object category, string factoryTypeName, string categoryTypeName, List<object> items)
        {
            CodeWriter writer = new();
            writer.AppendLine(AutoGeneratedHeader.TrimEnd());
            writer.AppendLine("namespace ET");
            writer.AppendLine("{");
            using (writer.PushIndent())
            {
                writer.AppendLine($"public sealed class {factoryTypeName} : IConfigFactory");
                writer.AppendLine("{");
                using (writer.PushIndent())
                {
                    writer.AppendLine($"public System.Type ConfigType => typeof(global::ET.{categoryTypeName});");
                    writer.AppendLine();
                    writer.AppendLine("public ASingleton Create()");
                    writer.AppendLine("{");
                    using (writer.PushIndent())
                    {
                        writer.AppendLine($"global::ET.{categoryTypeName} category = new global::ET.{categoryTypeName}();");
                        foreach (object item in items)
                        {
                            writer.AppendMultiline($"category.Add({ObjectInitializerEmitter.Emit(item, 0)});");
                        }

                        writer.AppendLine("return category;");
                    }
                    writer.AppendLine("}");
                }
                writer.AppendLine("}");
            }
            writer.AppendLine("}");
            return writer.ToString();
        }

        private static void WriteAllTextIfChanged(string path, string content)
        {
            if (File.Exists(path))
            {
                string existing = File.ReadAllText(path);
                if (string.Equals(existing, content, StringComparison.Ordinal))
                {
                    return;
                }
            }

            File.WriteAllText(path, content, new UTF8Encoding(false));
            Debug.Log($"Generated config factory: {path}");
        }

        private sealed class CodeWriter
        {
            private readonly StringBuilder sb = new();
            private int indent;

            public IDisposable PushIndent()
            {
                this.indent++;
                return new IndentScope(this);
            }

            public void AppendLine(string line = "")
            {
                if (line.Length == 0)
                {
                    this.sb.AppendLine();
                    return;
                }

                this.sb.Append(' ', this.indent * 4);
                this.sb.AppendLine(line);
            }

            public void AppendMultiline(string text)
            {
                string[] lines = text.Replace("\r\n", "\n").Split('\n');
                foreach (string line in lines)
                {
                    this.AppendLine(line);
                }
            }

            public override string ToString()
            {
                return this.sb.ToString();
            }

            private sealed class IndentScope : IDisposable
            {
                private readonly CodeWriter context;

                public IndentScope(CodeWriter context)
                {
                    this.context = context;
                }

                public void Dispose()
                {
                    this.context.indent--;
                }
            }
        }

        private static class ObjectInitializerEmitter
        {
            public static string Emit(object value, int indentLevel)
            {
                if (value == null)
                {
                    return "null";
                }

                Type type = value.GetType();
                if (TryFormatInlineValue(type, value, out string inlineValue))
                {
                    return inlineValue;
                }

                if (TryGetListElementType(type, out Type listElementType))
                {
                    return EmitList(type, listElementType, ((IEnumerable<object>)((System.Collections.IEnumerable)value).Cast<object>()).ToList(), indentLevel);
                }

                if (TryGetHashSetElementType(type, out Type hashSetElementType))
                {
                    return EmitHashSet(type, hashSetElementType, ((System.Collections.IEnumerable)value).Cast<object>().OrderBy(ComparableKey).ToList(), indentLevel);
                }

                if (type.IsArray)
                {
                    Type elementType = type.GetElementType()!;
                    return EmitArray(elementType, ((System.Collections.IEnumerable)value).Cast<object>().ToList(), indentLevel);
                }

                if (type.IsValueType)
                {
                    return EmitStruct(type, value, indentLevel);
                }

                return EmitObject(type, value, indentLevel);
            }

            private static string EmitObject(Type type, object value, int indentLevel)
            {
                List<string> members = new();
                foreach (FieldInfo field in EnumerateSerializableFields(type))
                {
                    object fieldValue = field.GetValue(value);
                    string expression = EmitFieldValue(field.FieldType, fieldValue, indentLevel + 1);
                    members.Add($"{Indent(indentLevel + 1)}{field.Name} = {expression},");
                }

                if (members.Count == 0)
                {
                    return $"new {ToCSharpTypeName(type)}()";
                }

                return
$@"new {ToCSharpTypeName(type)}
{{
{string.Join(Environment.NewLine, members)}
{Indent(indentLevel)}}}";
            }

            private static string EmitStruct(Type type, object value, int indentLevel)
            {
                if (TryFormatInlineValue(type, value, out string inlineValue))
                {
                    return inlineValue;
                }

                List<string> members = new();
                foreach (FieldInfo field in EnumerateSerializableFields(type))
                {
                    object fieldValue = field.GetValue(value);
                    string expression = EmitFieldValue(field.FieldType, fieldValue, indentLevel + 1);
                    members.Add($"{Indent(indentLevel + 1)}{field.Name} = {expression},");
                }

                if (members.Count == 0)
                {
                    return $"new {ToCSharpTypeName(type)}()";
                }

                return
$@"new {ToCSharpTypeName(type)}
{{
{string.Join(Environment.NewLine, members)}
{Indent(indentLevel)}}}";
            }

            private static string EmitList(Type listType, Type elementType, List<object> items, int indentLevel)
            {
                if (items.Count == 0)
                {
                    return $"new {ToCSharpTypeName(listType)}()";
                }

                List<string> members = items
                        .Select(item => $"{Indent(indentLevel + 1)}{EmitValueExpression(elementType, item, indentLevel + 1)},")
                        .ToList();

                return
$@"new {ToCSharpTypeName(listType)}
{{
{string.Join(Environment.NewLine, members)}
{Indent(indentLevel)}}}";
            }

            private static string EmitHashSet(Type hashSetType, Type elementType, List<object> items, int indentLevel)
            {
                if (items.Count == 0)
                {
                    return $"new {ToCSharpTypeName(hashSetType)}()";
                }

                List<string> members = items
                        .Select(item => $"{Indent(indentLevel + 1)}{EmitValueExpression(elementType, item, indentLevel + 1)},")
                        .ToList();

                return
$@"new {ToCSharpTypeName(hashSetType)}
{{
{string.Join(Environment.NewLine, members)}
{Indent(indentLevel)}}}";
            }

            private static string EmitArray(Type elementType, List<object> items, int indentLevel)
            {
                if (items.Count == 0)
                {
                    return $"new {ToCSharpTypeName(elementType)}[0]";
                }

                List<string> members = items
                        .Select(item => $"{Indent(indentLevel + 1)}{EmitValueExpression(elementType, item, indentLevel + 1)},")
                        .ToList();

                return
$@"new {ToCSharpTypeName(elementType)}[]
{{
{string.Join(Environment.NewLine, members)}
{Indent(indentLevel)}}}";
            }

            private static string EmitFieldValue(Type declaredType, object value, int indentLevel)
            {
                if (value == null)
                {
                    return "null";
                }

                if (TryFormatInlineValue(declaredType, value, out string inlineValue))
                {
                    return inlineValue;
                }

                return Emit(value, indentLevel);
            }

            private static string EmitValueExpression(Type declaredType, object value, int indentLevel)
            {
                if (value == null)
                {
                    return "null";
                }

                Type runtimeType = value.GetType();
                if (TryFormatInlineValue(runtimeType, value, out string inlineValue))
                {
                    return inlineValue;
                }

                return Emit(value, indentLevel);
            }

            private static string ComparableKey(object value)
            {
                if (value == null)
                {
                    return string.Empty;
                }

                return value switch
                {
                    Enum enumValue => $"{enumValue.GetType().FullName}:{Convert.ToInt64(enumValue, CultureInfo.InvariantCulture)}",
                    IFormattable formattable => formattable.ToString(null, CultureInfo.InvariantCulture),
                    _ => value.ToString(),
                };
            }

            private static string Indent(int level)
            {
                return new string(' ', level * 4);
            }
        }

        private static IEnumerable<FieldInfo> EnumerateSerializableFields(Type type)
        {
            if (type.BaseType != null && type.BaseType != typeof(object) && type.BaseType != typeof(ValueType))
            {
                foreach (FieldInfo field in EnumerateSerializableFields(type.BaseType))
                {
                    yield return field;
                }
            }

            FieldInfo[] currentFields = type.GetFields(BindingFlags.Instance | BindingFlags.Public | BindingFlags.DeclaredOnly);
            Array.Sort(currentFields, static (left, right) => left.MetadataToken.CompareTo(right.MetadataToken));
            foreach (FieldInfo field in currentFields)
            {
                if (!ShouldSerializeField(field))
                {
                    continue;
                }

                if (!RuntimeFieldExists(type, field.Name))
                {
                    continue;
                }

                yield return field;
            }
        }

        private static bool RuntimeFieldExists(Type editorType, string fieldName)
        {
            if (!RuntimeTypes.TryGetValue(editorType.FullName ?? string.Empty, out Type runtimeType))
            {
                return true;
            }

            return runtimeType.GetField(fieldName, BindingFlags.Instance | BindingFlags.Public | BindingFlags.DeclaredOnly) != null;
        }

        private static Dictionary<string, Type> LoadRuntimeTypes()
        {
            var result = new Dictionary<string, Type>();
            string projectRoot = Path.GetFullPath(Path.Combine(Application.dataPath, ".."));
            string[] assemblyPaths =
            {
                Path.Combine(projectRoot, "Bin/ET.Core.dll"),
                Path.Combine(projectRoot, "Bin/ET.Model.dll"),
                Path.Combine(projectRoot, "Bin/ET.Hotfix.dll"),
            };

            foreach (string assemblyPath in assemblyPaths)
            {
                if (!File.Exists(assemblyPath))
                {
                    continue;
                }

                try
                {
                    Assembly assembly = Assembly.LoadFrom(assemblyPath);
                    foreach (Type type in assembly.GetTypes())
                    {
                        if (type.FullName == null)
                        {
                            continue;
                        }

                        result[type.FullName] = type;
                    }
                }
                catch
                {
                    // ignore runtime assembly probe failures; exporter will fall back to editor-visible fields
                }
            }

            return result;
        }

        private static bool ShouldSerializeField(FieldInfo field)
        {
            if (field.IsStatic || field.IsLiteral || field.IsInitOnly)
            {
                return false;
            }

            if (field.IsNotSerialized)
            {
                return false;
            }

            if (field.GetCustomAttribute<BsonIgnoreAttribute>() != null)
            {
                return false;
            }

            return true;
        }

        private static bool TryGetListElementType(Type type, out Type elementType)
        {
            if (type.IsGenericType && type.GetGenericTypeDefinition() == typeof(List<>))
            {
                elementType = type.GetGenericArguments()[0];
                return true;
            }

            elementType = null;
            return false;
        }

        private static bool TryGetHashSetElementType(Type type, out Type elementType)
        {
            if (type.IsGenericType && type.GetGenericTypeDefinition() == typeof(HashSet<>))
            {
                elementType = type.GetGenericArguments()[0];
                return true;
            }

            elementType = null;
            return false;
        }

        private static bool TryFormatInlineValue(Type type, object value, out string code)
        {
            code = null;

            if (value == null)
            {
                code = "null";
                return true;
            }

            Type underlyingType = Nullable.GetUnderlyingType(type);
            if (underlyingType != null)
            {
                return TryFormatInlineValue(underlyingType, value, out code);
            }

            if (type == typeof(string))
            {
                code = "@\"" + ((string)value).Replace("\"", "\"\"") + "\"";
                return true;
            }

            if (type == typeof(bool))
            {
                code = (bool)value ? "true" : "false";
                return true;
            }

            if (type == typeof(char))
            {
                code = "'" + EscapeChar((char)value) + "'";
                return true;
            }

            if (type == typeof(byte))
            {
                code = ((byte)value).ToString(CultureInfo.InvariantCulture);
                return true;
            }

            if (type == typeof(sbyte))
            {
                code = $"(sbyte){((sbyte)value).ToString(CultureInfo.InvariantCulture)}";
                return true;
            }

            if (type == typeof(short))
            {
                code = $"(short){((short)value).ToString(CultureInfo.InvariantCulture)}";
                return true;
            }

            if (type == typeof(ushort))
            {
                code = $"(ushort){((ushort)value).ToString(CultureInfo.InvariantCulture)}";
                return true;
            }

            if (type == typeof(int))
            {
                code = ((int)value).ToString(CultureInfo.InvariantCulture);
                return true;
            }

            if (type == typeof(uint))
            {
                code = ((uint)value).ToString(CultureInfo.InvariantCulture) + "U";
                return true;
            }

            if (type == typeof(long))
            {
                code = ((long)value).ToString(CultureInfo.InvariantCulture) + "L";
                return true;
            }

            if (type == typeof(ulong))
            {
                code = ((ulong)value).ToString(CultureInfo.InvariantCulture) + "UL";
                return true;
            }

            if (type == typeof(float))
            {
                float number = (float)value;
                code = float.IsNaN(number)
                    ? "float.NaN"
                    : float.IsPositiveInfinity(number)
                        ? "float.PositiveInfinity"
                        : float.IsNegativeInfinity(number)
                            ? "float.NegativeInfinity"
                            : number.ToString("R", CultureInfo.InvariantCulture) + "f";
                return true;
            }

            if (type == typeof(double))
            {
                double number = (double)value;
                code = double.IsNaN(number)
                    ? "double.NaN"
                    : double.IsPositiveInfinity(number)
                        ? "double.PositiveInfinity"
                        : double.IsNegativeInfinity(number)
                            ? "double.NegativeInfinity"
                            : number.ToString("R", CultureInfo.InvariantCulture) + "d";
                return true;
            }

            if (type == typeof(decimal))
            {
                code = ((decimal)value).ToString(CultureInfo.InvariantCulture) + "m";
                return true;
            }

            if (type.IsEnum)
            {
                string enumName = Enum.GetName(type, value);
                if (!string.IsNullOrEmpty(enumName))
                {
                    code = $"{ToCSharpTypeName(type)}.{enumName}";
                    return true;
                }

                Type enumUnderlyingType = Enum.GetUnderlyingType(type);
                object numericValue = Convert.ChangeType(value, enumUnderlyingType, CultureInfo.InvariantCulture);
                code = $"({ToCSharpTypeName(type)}){Convert.ToString(numericValue, CultureInfo.InvariantCulture)}";
                return true;
            }

            return false;
        }

        private static string FormatStructValue(Type type, object value)
        {
            if (TryFormatInlineValue(type, value, out string inlineValue))
            {
                return inlineValue;
            }

            List<string> assignments = new();
            foreach (FieldInfo field in EnumerateSerializableFields(type))
            {
                object fieldValue = field.GetValue(value);
                if (fieldValue == null)
                {
                    assignments.Add($"{field.Name} = null");
                    continue;
                }

                Type fieldType = field.FieldType;
                string expression;
                if (TryFormatInlineValue(fieldType, fieldValue, out string formatted))
                {
                    expression = formatted;
                }
                else if (fieldType.IsValueType)
                {
                    expression = FormatStructValue(fieldType, fieldValue);
                }
                else
                {
                    throw new NotSupportedException($"Struct field type is not supported for inline emit: {fieldType.FullName}");
                }

                assignments.Add($"{field.Name} = {expression}");
            }

            if (assignments.Count == 0)
            {
                return $"new {ToCSharpTypeName(type)}()";
            }

            return $"new {ToCSharpTypeName(type)} {{ {string.Join(", ", assignments)} }}";
        }

        private static string EscapeChar(char value)
        {
            return value switch
            {
                '\'' => "\\'",
                '\\' => "\\\\",
                '\n' => "\\n",
                '\r' => "\\r",
                '\t' => "\\t",
                '\0' => "\\0",
                _ => value.ToString(),
            };
        }

        private static string ToCSharpTypeName(Type type)
        {
            if (type == typeof(void)) return "void";
            if (type == typeof(bool)) return "bool";
            if (type == typeof(byte)) return "byte";
            if (type == typeof(sbyte)) return "sbyte";
            if (type == typeof(short)) return "short";
            if (type == typeof(ushort)) return "ushort";
            if (type == typeof(int)) return "int";
            if (type == typeof(uint)) return "uint";
            if (type == typeof(long)) return "long";
            if (type == typeof(ulong)) return "ulong";
            if (type == typeof(float)) return "float";
            if (type == typeof(double)) return "double";
            if (type == typeof(decimal)) return "decimal";
            if (type == typeof(string)) return "string";
            if (type == typeof(object)) return "object";

            if (type.IsByRef)
            {
                type = type.GetElementType();
            }

            if (type.IsArray)
            {
                return $"{ToCSharpTypeName(type.GetElementType())}[]";
            }

            if (type.IsGenericType)
            {
                string genericTypeName = type.GetGenericTypeDefinition().FullName;
                genericTypeName = genericTypeName.Substring(0, genericTypeName.IndexOf('`'));
                Type[] args = type.GetGenericArguments();
                return $"global::{genericTypeName}<{string.Join(", ", Array.ConvertAll(args, ToCSharpTypeName))}>";
            }

            if (type.IsNested && type.DeclaringType != null)
            {
                return $"{ToCSharpTypeName(type.DeclaringType)}.{type.Name}";
            }

            return $"global::{type.FullName}";
        }

    }
}
