
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{

    [Config]
    public partial class NumericTypeConfigCategory : Singleton<NumericTypeConfigCategory>, ILubanConfig
    {
        private readonly Dictionary<int, NumericTypeConfig> _dataMap;
        private readonly List<NumericTypeConfig> _dataList;
        
        public NumericTypeConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, NumericTypeConfig>();
            _dataList = new List<NumericTypeConfig>();
            
            for(int n = _buf.ReadSize() ; n > 0 ; --n)
            {
                NumericTypeConfig _v;
                _v = NumericTypeConfig.DeserializeNumericTypeConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }
            EndInit();
        }

        public Dictionary<int, NumericTypeConfig> GetAll() => _dataMap;
        public Dictionary<int, NumericTypeConfig> DataMap => _dataMap;
        public List<NumericTypeConfig> DataList => _dataList;

        public NumericTypeConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);

        public NumericTypeConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            LubanLog.Error(this,key);
            return default;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
            EndRef();
        }


        partial void EndRef();
    }

}

