
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class UnitConfig : Luban.BeanBase
    {
        public UnitConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            Type = _buf.ReadInt();
            Name = _buf.ReadString();
            HeadIcon = _buf.ReadString();
            ClassType = (EClassType)_buf.ReadInt();
            {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);KV = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); KV[__index0] = __e0;}}

            EndInit();
        }

        public static UnitConfig DeserializeUnitConfig(ByteBuf _buf)
        {
            return new UnitConfig(_buf);
        }

        public readonly int Id;
        public readonly int Type;
        public readonly string Name;
        public readonly string HeadIcon;
        public readonly EClassType ClassType;
        public readonly int[] KV;
    
        public const int __ID__ = -568528378;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Type:" + Type + ","
            + "Name:" + Name + ","
            + "headIcon:" + HeadIcon + ","
            + "classType:" + ClassType + ","
            + "KV:" + Luban.StringUtil.CollectionToString(KV) + ","
            + "}";
        }

        partial void EndRef();
    }

}

