
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ET
{
    [EnableClass]
    public sealed partial class EquipmentConfig : Luban.BeanBase
    {
        public EquipmentConfig(JSONNode _buf) 
        {
            { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
            { if(!_buf["EquipSlot"].IsNumber) { throw new SerializationException(); }  EquipSlot = _buf["EquipSlot"]; }

            EndInit();
        }

        public static EquipmentConfig DeserializeEquipmentConfig(JSONNode _buf)
        {
            return new ET.EquipmentConfig(_buf);
        }

        /// <summary>
        /// ID
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 装备部位
        /// </summary>
        public readonly int EquipSlot;

        public const int __ID__ = -904342767;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "id:" + Id + ","
            + "EquipSlot:" + EquipSlot + ","
            + "}";
        }

        partial void EndRef();
    }

}

