
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ET
{
    [EnableClass]
    public sealed partial class MapConfig
    {
        public MapConfig(int Id, string Name, string Desc, ET.CopyType CopyType, string MapResName) 
        {
            this.Id = Id;
            this.Name = Name;
            this.Desc = Desc;
            this.CopyType = CopyType;
            this.MapResName = MapResName;
            EndInit();
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 地图名字
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// 描述
        /// </summary>
        public readonly string Desc;
        /// <summary>
        /// 副本类型
        /// </summary>
        public readonly ET.CopyType CopyType;
        /// <summary>
        /// 地图场景资源
        /// </summary>
        public readonly string MapResName;

        public  void ResolveRef()
        {
            EndRef();
        }

        partial void EndInit();
        partial void EndRef();
    }

}

