
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class MapConfig : Luban.BeanBase
    {
        public MapConfig(int Id, string Name, string Desc, ET.CopyType CopyType, string MapResName) 
        {
            this.Id = Id;
            this.Name = Name;
            this.Desc = Desc;
            this.CopyType = CopyType;
            this.MapResName = MapResName;
            EndInit();
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 地图名字
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// 描述
        /// </summary>
        public readonly string Desc;
        /// <summary>
        /// 副本类型
        /// </summary>
        public readonly ET.CopyType CopyType;
        /// <summary>
        /// 地图场景资源
        /// </summary>
        public readonly string MapResName;

        public const int __ID__ = 1701072159;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(Tables tables)
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "Desc:" + Desc + ","
            + "CopyType:" + CopyType + ","
            + "MapResName:" + MapResName + ","
            + "}";
        }

        partial void EndRef();
    }

}

