
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ET
{
    [EnableClass]
    public sealed partial class NumericTypeConfig
    {
        public NumericTypeConfig(int Id, string Name, int MaxNumericType, System.Collections.Generic.Dictionary<int, long> AffectNumeric) 
        {
            this.Id = Id;
            this.Name = Name;
            this.MaxNumericType = MaxNumericType;
            this.AffectNumeric = AffectNumeric;
            EndInit();
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 名字
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// 对应的最大值属性
        /// </summary>
        public readonly int MaxNumericType;
        /// <summary>
        /// 影响的属性id
        /// </summary>
        public readonly System.Collections.Generic.Dictionary<int, long> AffectNumeric;

        public  void ResolveRef()
        {
            EndRef();
        }

        partial void EndInit();
        partial void EndRef();
    }

}

