
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class QuestObjectiveParams_KillMonster : ET.QuestObjectiveParams
    {
        public QuestObjectiveParams_KillMonster(int MonsterId)  : base()
        {
            this.MonsterId = MonsterId;
            EndInit();
        }

        /// <summary>
        /// 击杀的怪物Id
        /// </summary>
        public readonly int MonsterId;

        public const int __ID__ = -933968487;
        public override int GetTypeId() => __ID__;

        public override void ResolveRef(Tables tables)
        {
            base.ResolveRef(tables);
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "MonsterId:" + MonsterId + ","
            + "}";
        }

        partial void EndRef();
    }

}

