
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class QuestConfig : Luban.BeanBase
    {
        public QuestConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            Desc = _buf.ReadString();
            {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);ObjectiveIds = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); ObjectiveIds[__index0] = __e0;}}
            {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);PreQuestIds = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); PreQuestIds[__index0] = __e0;}}
            {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);NextQuestId = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); NextQuestId[__index0] = __e0;}}
            Title = _buf.ReadString();
            Content = _buf.ReadString();
            FinishContent = _buf.ReadString();
            AcceptNPC = _buf.ReadInt();
            AcceptNPCMap = _buf.ReadInt();
            SubmitNPC = _buf.ReadInt();
            SubmitNPCMap = _buf.ReadInt();

            EndInit();
        }

        public static QuestConfig DeserializeQuestConfig(ByteBuf _buf)
        {
            return new ET.QuestConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 任务名字
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// 任务描述
        /// </summary>
        public readonly string Desc;
        /// <summary>
        /// 任务目标
        /// </summary>
        public readonly int[] ObjectiveIds;
        /// <summary>
        /// 前置任务
        /// </summary>
        public readonly int[] PreQuestIds;
        /// <summary>
        /// 后置任务
        /// </summary>
        public readonly int[] NextQuestId;
        /// <summary>
        /// 任务标题
        /// </summary>
        public readonly string Title;
        /// <summary>
        /// 任务文本
        /// </summary>
        public readonly string Content;
        /// <summary>
        /// 任务完成文本
        /// </summary>
        public readonly string FinishContent;
        /// <summary>
        /// 接任务NPC
        /// </summary>
        public readonly int AcceptNPC;
        /// <summary>
        /// 接任务NPC地图
        /// </summary>
        public readonly int AcceptNPCMap;
        /// <summary>
        /// 交任务NPC
        /// </summary>
        public readonly int SubmitNPC;
        /// <summary>
        /// 交任务NPC地图
        /// </summary>
        public readonly int SubmitNPCMap;
    
        public const int __ID__ = -507727899;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "Desc:" + Desc + ","
            + "ObjectiveIds:" + Luban.StringUtil.CollectionToString(ObjectiveIds) + ","
            + "PreQuestIds:" + Luban.StringUtil.CollectionToString(PreQuestIds) + ","
            + "NextQuestId:" + Luban.StringUtil.CollectionToString(NextQuestId) + ","
            + "Title:" + Title + ","
            + "Content:" + Content + ","
            + "FinishContent:" + FinishContent + ","
            + "AcceptNPC:" + AcceptNPC + ","
            + "AcceptNPCMap:" + AcceptNPCMap + ","
            + "SubmitNPC:" + SubmitNPC + ","
            + "SubmitNPCMap:" + SubmitNPCMap + ","
            + "}";
        }

        partial void EndRef();
    }

}

