
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ET
{
    [EnableClass]
    public sealed partial class QuestConfig : Luban.BeanBase
    {
        public QuestConfig(JSONNode _buf) 
        {
            { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
            { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
            { if(!_buf["Desc"].IsString) { throw new SerializationException(); }  Desc = _buf["Desc"]; }
            { var __json0 = _buf["ObjectiveIds"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; ObjectiveIds = new int[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  ObjectiveIds[__index0++] = __v0; }   }
            { var __json0 = _buf["PreQuestIds"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; PreQuestIds = new int[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  PreQuestIds[__index0++] = __v0; }   }
            { var __json0 = _buf["NextQuestId"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; NextQuestId = new int[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  NextQuestId[__index0++] = __v0; }   }
            { if(!_buf["Title"].IsString) { throw new SerializationException(); }  Title = _buf["Title"]; }
            { if(!_buf["Content"].IsString) { throw new SerializationException(); }  Content = _buf["Content"]; }
            { if(!_buf["AcceptedContent"].IsString) { throw new SerializationException(); }  AcceptedContent = _buf["AcceptedContent"]; }
            { if(!_buf["FinishContent"].IsString) { throw new SerializationException(); }  FinishContent = _buf["FinishContent"]; }
            { if(!_buf["AcceptNPC"].IsNumber) { throw new SerializationException(); }  AcceptNPC = _buf["AcceptNPC"]; }
            { if(!_buf["AcceptNPCMap"].IsString) { throw new SerializationException(); }  AcceptNPCMap = _buf["AcceptNPCMap"]; }
            { if(!_buf["SubmitNPC"].IsNumber) { throw new SerializationException(); }  SubmitNPC = _buf["SubmitNPC"]; }
            { if(!_buf["SubmitNPCMap"].IsString) { throw new SerializationException(); }  SubmitNPCMap = _buf["SubmitNPCMap"]; }

            EndInit();
        }

        public static QuestConfig DeserializeQuestConfig(JSONNode _buf)
        {
            return new ET.QuestConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 任务名字
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// 任务描述
        /// </summary>
        public readonly string Desc;
        /// <summary>
        /// 任务目标
        /// </summary>
        public readonly int[] ObjectiveIds;
        /// <summary>
        /// 前置任务
        /// </summary>
        public readonly int[] PreQuestIds;
        /// <summary>
        /// 后置任务
        /// </summary>
        public readonly int[] NextQuestId;
        /// <summary>
        /// 任务标题
        /// </summary>
        public readonly string Title;
        /// <summary>
        /// 任务文本
        /// </summary>
        public readonly string Content;
        /// <summary>
        /// 已接任务文本
        /// </summary>
        public readonly string AcceptedContent;
        /// <summary>
        /// 任务完成文本
        /// </summary>
        public readonly string FinishContent;
        /// <summary>
        /// 接任务NPC
        /// </summary>
        public readonly int AcceptNPC;
        /// <summary>
        /// 接任务NPC地图
        /// </summary>
        public readonly string AcceptNPCMap;
        /// <summary>
        /// 交任务NPC
        /// </summary>
        public readonly int SubmitNPC;
        /// <summary>
        /// 交任务NPC地图
        /// </summary>
        public readonly string SubmitNPCMap;

        public const int __ID__ = -507727899;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "Desc:" + Desc + ","
            + "ObjectiveIds:" + Luban.StringUtil.CollectionToString(ObjectiveIds) + ","
            + "PreQuestIds:" + Luban.StringUtil.CollectionToString(PreQuestIds) + ","
            + "NextQuestId:" + Luban.StringUtil.CollectionToString(NextQuestId) + ","
            + "Title:" + Title + ","
            + "Content:" + Content + ","
            + "AcceptedContent:" + AcceptedContent + ","
            + "FinishContent:" + FinishContent + ","
            + "AcceptNPC:" + AcceptNPC + ","
            + "AcceptNPCMap:" + AcceptNPCMap + ","
            + "SubmitNPC:" + SubmitNPC + ","
            + "SubmitNPCMap:" + SubmitNPCMap + ","
            + "}";
        }

        partial void EndRef();
    }

}

