
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
public partial class TextConfigCategory
{
    private readonly System.Collections.Generic.Dictionary<int, ET.TextConfig> _dataMap;
    private readonly System.Collections.Generic.List<ET.TextConfig> _dataList;

    public System.Collections.Generic.IReadOnlyDictionary<int, ET.TextConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<ET.TextConfig> DataList => _dataList;
    public ET.TextConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public ET.TextConfig Get(int key) => _dataMap[key];
    public ET.TextConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach (var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

    partial void PostInit();
}
}

