
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class TextConfig : Luban.BeanBase
    {
        public TextConfig(int Id, string Name, string CN, string EN) 
        {
            this.Id = Id;
            this.Name = Name;
            this.CN = CN;
            this.EN = EN;
            EndInit();
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 名字
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// 中文
        /// </summary>
        public readonly string CN;
        /// <summary>
        /// 英文
        /// </summary>
        public readonly string EN;

        public const int __ID__ = 1515216270;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(Tables tables)
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "CN:" + CN + ","
            + "EN:" + EN + ","
            + "}";
        }

        partial void EndRef();
    }

}

