
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class UnitConfig : Luban.BeanBase
    {
        public UnitConfig(int Id, ET.UnitType UnitType, string Name, string HeadIcon, ET.EClassType ClassType) 
        {
            this.Id = Id;
            this.UnitType = UnitType;
            this.Name = Name;
            this.HeadIcon = HeadIcon;
            this.ClassType = ClassType;
            EndInit();
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// Type
        /// </summary>
        public readonly ET.UnitType UnitType;
        /// <summary>
        /// 名字
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// 头像图片
        /// </summary>
        public readonly string HeadIcon;
        /// <summary>
        /// 职业
        /// </summary>
        public readonly ET.EClassType ClassType;

        public const int __ID__ = 1859130533;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "UnitType:" + UnitType + ","
            + "Name:" + Name + ","
            + "headIcon:" + HeadIcon + ","
            + "classType:" + ClassType + ","
            + "}";
        }

        partial void EndRef();
    }

}

