
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ET
{
    [EnableClass]
    public sealed partial class EquipmentConfig : Luban.BeanBase
    {
        public EquipmentConfig(JSONNode _buf) 
        {
            { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
            { if(!_buf["EquipSlot"].IsNumber) { throw new SerializationException(); }  EquipSlot = _buf["EquipSlot"]; }
            { var __json0 = _buf["KV"]; if(!__json0.IsArray) { throw new SerializationException(); } KV = new System.Collections.Generic.Dictionary<int, long>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int _k0;  { if(!__e0[0].IsNumber) { throw new SerializationException(); }  _k0 = __e0[0]; } long _v0;  { if(!__e0[1].IsNumber) { throw new SerializationException(); }  _v0 = __e0[1]; }  KV.Add(_k0, _v0); }   }

            EndInit();
        }

        public static EquipmentConfig DeserializeEquipmentConfig(JSONNode _buf)
        {
            return new ET.EquipmentConfig(_buf);
        }

        /// <summary>
        /// ID
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 装备部位
        /// </summary>
        public readonly int EquipSlot;
        /// <summary>
        /// 速度Base
        /// </summary>
        public readonly System.Collections.Generic.Dictionary<int, long> KV;

        public const int __ID__ = -904342767;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "id:" + Id + ","
            + "EquipSlot:" + EquipSlot + ","
            + "KV:" + Luban.StringUtil.CollectionToString(KV) + ","
            + "}";
        }

        partial void EndRef();
    }

}

