
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class ItemConfig : Luban.BeanBase
    {
        public ItemConfig(int Id, string Name, int Type, int MaxStack, int Quality, int UseType, int Level) 
        {
            this.Id = Id;
            this.Name = Name;
            this.Type = Type;
            this.MaxStack = MaxStack;
            this.Quality = Quality;
            this.UseType = UseType;
            this.Level = Level;
            EndInit();
        }

        /// <summary>
        /// ID
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 名称
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// 类型
        /// </summary>
        public readonly int Type;
        /// <summary>
        /// 最大堆叠
        /// </summary>
        public readonly int MaxStack;
        /// <summary>
        /// 品质
        /// </summary>
        public readonly int Quality;
        /// <summary>
        /// 使用类型
        /// </summary>
        public readonly int UseType;
        /// <summary>
        /// 等级
        /// </summary>
        public readonly int Level;

        public const int __ID__ = 1663635188;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(Tables tables)
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "Type:" + Type + ","
            + "MaxStack:" + MaxStack + ","
            + "Quality:" + Quality + ","
            + "UseType:" + UseType + ","
            + "Level:" + Level + ","
            + "}";
        }

        partial void EndRef();
    }

}

