
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ET
{
    [EnableClass]
    public sealed partial class MapConfig : Luban.BeanBase
    {
        public MapConfig(JSONNode _buf) 
        {
            { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
            { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
            { if(!_buf["Desc"].IsString) { throw new SerializationException(); }  Desc = _buf["Desc"]; }
            { if(!_buf["CopyType"].IsNumber) { throw new SerializationException(); }  CopyType = (ET.CopyType)_buf["CopyType"].AsInt; }
            { if(!_buf["MaxLineNum"].IsNumber) { throw new SerializationException(); }  MaxLineNum = _buf["MaxLineNum"]; }
            { if(!_buf["MaxPlayerNum"].IsNumber) { throw new SerializationException(); }  MaxPlayerNum = _buf["MaxPlayerNum"]; }
            { if(!_buf["RecommendPlayerNum"].IsNumber) { throw new SerializationException(); }  RecommendPlayerNum = _buf["RecommendPlayerNum"]; }
            { if(!_buf["MapResName"].IsString) { throw new SerializationException(); }  MapResName = _buf["MapResName"]; }

            EndInit();
        }

        public static MapConfig DeserializeMapConfig(JSONNode _buf)
        {
            return new ET.MapConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 地图名字
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// 描述
        /// </summary>
        public readonly string Desc;
        /// <summary>
        /// 副本类型
        /// </summary>
        public readonly ET.CopyType CopyType;
        /// <summary>
        /// 最大分线数量
        /// </summary>
        public readonly int MaxLineNum;
        /// <summary>
        /// 单线最大人数
        /// </summary>
        public readonly int MaxPlayerNum;
        /// <summary>
        /// 推荐人数，超过开新线
        /// </summary>
        public readonly int RecommendPlayerNum;
        /// <summary>
        /// 地图场景资源
        /// </summary>
        public readonly string MapResName;

        public const int __ID__ = 1701072159;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "Desc:" + Desc + ","
            + "CopyType:" + CopyType + ","
            + "MaxLineNum:" + MaxLineNum + ","
            + "MaxPlayerNum:" + MaxPlayerNum + ","
            + "RecommendPlayerNum:" + RecommendPlayerNum + ","
            + "MapResName:" + MapResName + ","
            + "}";
        }

        partial void EndRef();
    }

}

