
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class MapUnitConfig : Luban.BeanBase
    {
        public MapUnitConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            UnitConfigId = _buf.ReadInt();
            MapName = _buf.ReadString();
            {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);KV = new System.Collections.Generic.Dictionary<int, long>(n0 * 3 / 2);for(var i0 = 0 ; i0 < n0 ; i0++) { int _k0;  _k0 = _buf.ReadInt(); long _v0;  _v0 = _buf.ReadLong();     KV.Add(_k0, _v0);}}

            EndInit();
        }

        public static MapUnitConfig DeserializeMapUnitConfig(ByteBuf _buf)
        {
            return new ET.MapUnitConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// UnitConfigId
        /// </summary>
        public readonly int UnitConfigId;
        /// <summary>
        /// 所在地图
        /// </summary>
        public readonly string MapName;
        /// <summary>
        /// 出生X坐标
        /// </summary>
        public readonly System.Collections.Generic.Dictionary<int, long> KV;
    
        public const int __ID__ = -2012370621;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "UnitConfigId:" + UnitConfigId + ","
            + "MapName:" + MapName + ","
            + "KV:" + Luban.StringUtil.CollectionToString(KV) + ","
            + "}";
        }

        partial void EndRef();
    }

}

