
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class NumericTypeConfig : Luban.BeanBase
    {
        public NumericTypeConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            NeedSaveDB = _buf.ReadInt();
            NoticeType = (ET.NoticeType)_buf.ReadInt();
            MaxNumericType = _buf.ReadInt();
            {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);AffectNumeric = new System.Collections.Generic.Dictionary<int, long>(n0 * 3 / 2);for(var i0 = 0 ; i0 < n0 ; i0++) { int _k0;  _k0 = _buf.ReadInt(); long _v0;  _v0 = _buf.ReadLong();     AffectNumeric.Add(_k0, _v0);}}

            EndInit();
        }

        public static NumericTypeConfig DeserializeNumericTypeConfig(ByteBuf _buf)
        {
            return new ET.NumericTypeConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 名字
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// 是否存数据库
        /// </summary>
        public readonly int NeedSaveDB;
        /// <summary>
        /// 广播给客户端类型
        /// </summary>
        public readonly ET.NoticeType NoticeType;
        /// <summary>
        /// 对应的最大值属性
        /// </summary>
        public readonly int MaxNumericType;
        /// <summary>
        /// 影响的属性id
        /// </summary>
        public readonly System.Collections.Generic.Dictionary<int, long> AffectNumeric;
    
        public const int __ID__ = 1076638314;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "NeedSaveDB:" + NeedSaveDB + ","
            + "NoticeType:" + NoticeType + ","
            + "MaxNumericType:" + MaxNumericType + ","
            + "AffectNumeric:" + Luban.StringUtil.CollectionToString(AffectNumeric) + ","
            + "}";
        }

        partial void EndRef();
    }

}

