
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ET
{
    [EnableClass]
    public sealed partial class NumericTypeConfig : Luban.BeanBase
    {
        public NumericTypeConfig(JSONNode _buf) 
        {
            { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
            { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
            { if(!_buf["NeedSaveDB"].IsNumber) { throw new SerializationException(); }  NeedSaveDB = _buf["NeedSaveDB"]; }
            { if(!_buf["NoticeType"].IsNumber) { throw new SerializationException(); }  NoticeType = (NoticeType)_buf["NoticeType"].AsInt; }
            { if(!_buf["MaxNumericType"].IsNumber) { throw new SerializationException(); }  MaxNumericType = _buf["MaxNumericType"]; }
            { var __json0 = _buf["AffectNumeric"]; if(!__json0.IsArray) { throw new SerializationException(); } AffectNumeric = new System.Collections.Generic.Dictionary<int, long>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int _k0;  { if(!__e0[0].IsNumber) { throw new SerializationException(); }  _k0 = __e0[0]; } long _v0;  { if(!__e0[1].IsNumber) { throw new SerializationException(); }  _v0 = __e0[1]; }  AffectNumeric.Add(_k0, _v0); }   }

            EndInit();
        }

        public static NumericTypeConfig DeserializeNumericTypeConfig(JSONNode _buf)
        {
            return new ET.NumericTypeConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 名字
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// 是否存数据库
        /// </summary>
        public readonly int NeedSaveDB;
        /// <summary>
        /// 广播给客户端类型
        /// </summary>
        public readonly NoticeType NoticeType;
        /// <summary>
        /// 对应的最大值属性
        /// </summary>
        public readonly int MaxNumericType;
        /// <summary>
        /// 影响的属性id
        /// </summary>
        public readonly System.Collections.Generic.Dictionary<int, long> AffectNumeric;

        public const int __ID__ = 1076638314;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "NeedSaveDB:" + NeedSaveDB + ","
            + "NoticeType:" + NoticeType + ","
            + "MaxNumericType:" + MaxNumericType + ","
            + "AffectNumeric:" + Luban.StringUtil.CollectionToString(AffectNumeric) + ","
            + "}";
        }

        partial void EndRef();
    }

}

