
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
[ConfigProcess(ConfigType.Code)]
public partial class NumericTypeConfigCategory : Singleton<NumericTypeConfigCategory>, IConfig
{
    private readonly System.Collections.Generic.Dictionary<int, ET.NumericTypeConfig> _dataMap;

    public NumericTypeConfigCategory(System.Collections.Generic.Dictionary<int, ET.NumericTypeConfig> dataMap)
    {
        _dataMap = dataMap;
        EndInit();
    }

    public System.Collections.Generic.Dictionary<int, ET.NumericTypeConfig> GetAll() => _dataMap;
    public System.Collections.Generic.IReadOnlyDictionary<int, ET.NumericTypeConfig> DataMap => _dataMap;
    public ET.NumericTypeConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public ET.NumericTypeConfig Get(int key) => _dataMap[key];
    public ET.NumericTypeConfig this[int key] => _dataMap[key];

    public void ResolveRef()
    {
        foreach (var _v in _dataMap.Values)
        {
            _v.ResolveRef();
        }
        EndRef();
    }

    partial void EndRef();
}
}

