
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ET
{
[ConfigProcess(ConfigType.Code)]
public partial class QuestConfigCategory : Singleton<QuestConfigCategory>, IConfig
{
    private readonly System.Collections.Generic.Dictionary<int, ET.QuestConfig> _dataMap;

    public QuestConfigCategory(System.Collections.Generic.Dictionary<int, ET.QuestConfig> dataMap)
    {
        _dataMap = dataMap;
        EndInit();
    }

    public System.Collections.Generic.Dictionary<int, ET.QuestConfig> GetAll() => _dataMap;
    public System.Collections.Generic.IReadOnlyDictionary<int, ET.QuestConfig> DataMap => _dataMap;
    public ET.QuestConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public ET.QuestConfig Get(int key) => _dataMap[key];
    public ET.QuestConfig this[int key] => _dataMap[key];

    public void ResolveRef()
    {
        foreach (var _v in _dataMap.Values)
        {
            _v.ResolveRef();
        }
        EndRef();
    }

    partial void EndRef();
}
}

