
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ET
{
    [EnableClass]
    public sealed partial class QuestObjectiveConfig : Luban.BeanBase
    {
        public QuestObjectiveConfig(JSONNode _buf) 
        {
            { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
            { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
            { if(!_buf["Desc"].IsString) { throw new SerializationException(); }  Desc = _buf["Desc"]; }
            { if(!_buf["Type"].IsNumber) { throw new SerializationException(); }  Type = (ET.QuestObjectiveType)_buf["Type"].AsInt; }
            { if(!_buf["NeedCount"].IsNumber) { throw new SerializationException(); }  NeedCount = _buf["NeedCount"]; }
            { if(!_buf["Params"].IsObject) { throw new SerializationException(); }  Params = global::ET.QuestObjectiveParams.DeserializeQuestObjectiveParams(_buf["Params"]);  }

            EndInit();
        }

        public static QuestObjectiveConfig DeserializeQuestObjectiveConfig(JSONNode _buf)
        {
            return new ET.QuestObjectiveConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 任务目标名字
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// 任务描述
        /// </summary>
        public readonly string Desc;
        /// <summary>
        /// 任务类型
        /// </summary>
        public readonly ET.QuestObjectiveType Type;
        /// <summary>
        /// 需要的数量
        /// </summary>
        public readonly int NeedCount;
        /// <summary>
        /// 任务目标参数
        /// </summary>
        public readonly ET.QuestObjectiveParams Params;

        public const int __ID__ = -70847336;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            Params?.ResolveRef();
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "Desc:" + Desc + ","
            + "Type:" + Type + ","
            + "NeedCount:" + NeedCount + ","
            + "Params:" + Params + ","
            + "}";
        }

        partial void EndRef();
    }

}

