
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class QuestConfig : Luban.BeanBase
    {
        public QuestConfig(int Id, string Name, string Desc, int[] ObjectiveIds, int[] PreQuestIds, int[] NextQuestId, string Title, string Content, string AcceptedContent, string FinishContent, int AcceptNPC, string AcceptNPCMap, int SubmitNPC, string SubmitNPCMap) 
        {
            this.Id = Id;
            this.Name = Name;
            this.Desc = Desc;
            this.ObjectiveIds = ObjectiveIds;
            this.PreQuestIds = PreQuestIds;
            this.NextQuestId = NextQuestId;
            this.Title = Title;
            this.Content = Content;
            this.AcceptedContent = AcceptedContent;
            this.FinishContent = FinishContent;
            this.AcceptNPC = AcceptNPC;
            this.AcceptNPCMap = AcceptNPCMap;
            this.SubmitNPC = SubmitNPC;
            this.SubmitNPCMap = SubmitNPCMap;
            EndInit();
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 任务名字
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// 任务描述
        /// </summary>
        public readonly string Desc;
        /// <summary>
        /// 任务目标
        /// </summary>
        public readonly int[] ObjectiveIds;
        /// <summary>
        /// 前置任务
        /// </summary>
        public readonly int[] PreQuestIds;
        /// <summary>
        /// 后置任务
        /// </summary>
        public readonly int[] NextQuestId;
        /// <summary>
        /// 任务标题
        /// </summary>
        public readonly string Title;
        /// <summary>
        /// 任务文本
        /// </summary>
        public readonly string Content;
        /// <summary>
        /// 已接任务文本
        /// </summary>
        public readonly string AcceptedContent;
        /// <summary>
        /// 任务完成文本
        /// </summary>
        public readonly string FinishContent;
        /// <summary>
        /// 接任务NPC
        /// </summary>
        public readonly int AcceptNPC;
        /// <summary>
        /// 接任务NPC地图
        /// </summary>
        public readonly string AcceptNPCMap;
        /// <summary>
        /// 交任务NPC
        /// </summary>
        public readonly int SubmitNPC;
        /// <summary>
        /// 交任务NPC地图
        /// </summary>
        public readonly string SubmitNPCMap;

        public const int __ID__ = -507727899;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(Tables tables)
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "Desc:" + Desc + ","
            + "ObjectiveIds:" + Luban.StringUtil.CollectionToString(ObjectiveIds) + ","
            + "PreQuestIds:" + Luban.StringUtil.CollectionToString(PreQuestIds) + ","
            + "NextQuestId:" + Luban.StringUtil.CollectionToString(NextQuestId) + ","
            + "Title:" + Title + ","
            + "Content:" + Content + ","
            + "AcceptedContent:" + AcceptedContent + ","
            + "FinishContent:" + FinishContent + ","
            + "AcceptNPC:" + AcceptNPC + ","
            + "AcceptNPCMap:" + AcceptNPCMap + ","
            + "SubmitNPC:" + SubmitNPC + ","
            + "SubmitNPCMap:" + SubmitNPCMap + ","
            + "}";
        }

        partial void EndRef();
    }

}

