
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ET
{
    [EnableClass]
    public sealed partial class UnitConfig : Luban.BeanBase
    {
        public UnitConfig(JSONNode _buf) 
        {
            { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
            { if(!_buf["UnitType"].IsNumber) { throw new SerializationException(); }  UnitType = (ET.UnitType)_buf["UnitType"].AsInt; }
            { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
            { if(!_buf["class_type"].IsNumber) { throw new SerializationException(); }  ClassType = (ET.EClassType)_buf["class_type"].AsInt; }
            { var __json0 = _buf["KV"]; if(!__json0.IsArray) { throw new SerializationException(); } KV = new System.Collections.Generic.Dictionary<int, long>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int _k0;  { if(!__e0[0].IsNumber) { throw new SerializationException(); }  _k0 = __e0[0]; } long _v0;  { if(!__e0[1].IsNumber) { throw new SerializationException(); }  _v0 = __e0[1]; }  KV.Add(_k0, _v0); }   }

            EndInit();
        }

        public static UnitConfig DeserializeUnitConfig(JSONNode _buf)
        {
            return new ET.UnitConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// Type
        /// </summary>
        public readonly ET.UnitType UnitType;
        /// <summary>
        /// 名字
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// 职业
        /// </summary>
        public readonly ET.EClassType ClassType;
        /// <summary>
        /// 速度Base
        /// </summary>
        public readonly System.Collections.Generic.Dictionary<int, long> KV;

        public const int __ID__ = 1859130533;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "UnitType:" + UnitType + ","
            + "Name:" + Name + ","
            + "classType:" + ClassType + ","
            + "KV:" + Luban.StringUtil.CollectionToString(KV) + ","
            + "}";
        }

        partial void EndRef();
    }

}

