
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET.Server
{
    [EnableClass]
    public sealed partial class StartSceneConfig : Luban.BeanBase
    {
        public StartSceneConfig(int Id, int Process, int Zone, string SceneType, string Name, int Port) 
        {
            this.Id = Id;
            this.Process = Process;
            this.Zone = Zone;
            this.SceneType = SceneType;
            this.Name = Name;
            this.Port = Port;
            EndInit();
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 所属进程
        /// </summary>
        public readonly int Process;
        /// <summary>
        /// 所属区
        /// </summary>
        public readonly int Zone;
        /// <summary>
        /// 类型
        /// </summary>
        public readonly string SceneType;
        /// <summary>
        /// 名字
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// 外网端口
        /// </summary>
        public readonly int Port;

        public const int __ID__ = 777443384;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Process:" + Process + ","
            + "Zone:" + Zone + ","
            + "SceneType:" + SceneType + ","
            + "Name:" + Name + ","
            + "Port:" + Port + ","
            + "}";
        }

        partial void EndRef();
    }

}

