
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ET.Server
{
    [EnableClass]
    public sealed partial class StartSceneConfig
    {
        public StartSceneConfig(int Id, int Process, int Zone, string SceneType, string Name, int Port) 
        {
            this.Id = Id;
            this.Process = Process;
            this.Zone = Zone;
            this.SceneType = SceneType;
            this.Name = Name;
            this.Port = Port;
            EndInit();
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 所属进程
        /// </summary>
        public readonly int Process;
        /// <summary>
        /// 所属区
        /// </summary>
        public readonly int Zone;
        /// <summary>
        /// 类型
        /// </summary>
        public readonly string SceneType;
        /// <summary>
        /// 名字
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// 外网端口
        /// </summary>
        public readonly int Port;

        public  void ResolveRef()
        {
            EndRef();
        }

        partial void EndInit();
        partial void EndRef();
    }

}

