
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;
using MongoDB.Bson.Serialization.Attributes;
using MongoDB.Bson.Serialization.Options;
using SimpleJSON;

namespace ET.Server
{

    [ConfigProcess(ConfigType.Json)]
    public partial class StartMachineConfigCategory : Singleton<StartMachineConfigCategory>, IConfig
    {
        [BsonElement]
        [BsonDictionaryOptions(DictionaryRepresentation.ArrayOfArrays)]
        private readonly Dictionary<int, ET.Server.StartMachineConfig> _dataMap;
        private readonly List<ET.Server.StartMachineConfig> _dataList;

        public StartMachineConfigCategory(JSONNode _buf)
        {
            _dataMap = new Dictionary<int, ET.Server.StartMachineConfig>();
            _dataList = new List<ET.Server.StartMachineConfig>();

            foreach(JSONNode _ele in _buf.Children)
            {
                ET.Server.StartMachineConfig _v;
                { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::ET.Server.StartMachineConfig.DeserializeStartMachineConfig(_ele);  }
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }
            EndInit();
        }

        public Dictionary<int, ET.Server.StartMachineConfig> GetAll() => _dataMap;
        public Dictionary<int, ET.Server.StartMachineConfig> DataMap => _dataMap;
        public List<ET.Server.StartMachineConfig> DataList => _dataList;

        public ET.Server.StartMachineConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);

        public ET.Server.StartMachineConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            throw new System.Exception($"not found config: {this.GetType().FullName}, key: {key}");
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
            EndRef();
        }


        partial void EndRef();
    }

}

