
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET.Server
{
    [EnableClass]
    public sealed partial class StartMachineConfig : Luban.BeanBase
    {
        public StartMachineConfig(int Id, string InnerIP, string OuterIP) 
        {
            this.Id = Id;
            this.InnerIP = InnerIP;
            this.OuterIP = OuterIP;
            EndInit();
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 内网地址
        /// </summary>
        public readonly string InnerIP;
        /// <summary>
        /// 外网地址
        /// </summary>
        public readonly string OuterIP;

        public const int __ID__ = -737091277;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "InnerIP:" + InnerIP + ","
            + "OuterIP:" + OuterIP + ","
            + "}";
        }

        partial void EndRef();
    }

}

