
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;
using MongoDB.Bson.Serialization.Attributes;
using MongoDB.Bson.Serialization.Options;

namespace ET.Server
{

    [ConfigProcess]
    public partial class StartZoneConfigCategory : Singleton<StartZoneConfigCategory>, IConfig
    {
        [BsonElement]
        [BsonDictionaryOptions(DictionaryRepresentation.ArrayOfArrays)]
        private readonly Dictionary<int, ET.Server.StartZoneConfig> _dataMap;
        private readonly List<ET.Server.StartZoneConfig> _dataList;
        
        public StartZoneConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, ET.Server.StartZoneConfig>();
            _dataList = new List<ET.Server.StartZoneConfig>();
            
            for(int n = _buf.ReadSize() ; n > 0 ; --n)
            {
                ET.Server.StartZoneConfig _v;
                _v = global::ET.Server.StartZoneConfig.DeserializeStartZoneConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }
            EndInit();
        }

        public Dictionary<int, ET.Server.StartZoneConfig> GetAll() => _dataMap;
        public Dictionary<int, ET.Server.StartZoneConfig> DataMap => _dataMap;
        public List<ET.Server.StartZoneConfig> DataList => _dataList;

        public ET.Server.StartZoneConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);

        public ET.Server.StartZoneConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            LubanLog.Error(this,key);
            return default;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
            EndRef();
        }


        partial void EndRef();
    }

}

