
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ET.Server
{
[ConfigProcess(ConfigType.Code)]
public partial class StartSceneConfigCategory : Singleton<StartSceneConfigCategory>, IConfig
{
    private readonly System.Collections.Generic.Dictionary<int, ET.Server.StartSceneConfig> _dataMap;

    public StartSceneConfigCategory(System.Collections.Generic.Dictionary<int, ET.Server.StartSceneConfig> dataMap)
    {
        _dataMap = dataMap;
        EndInit();
    }

    public System.Collections.Generic.Dictionary<int, ET.Server.StartSceneConfig> GetAll() => _dataMap;
    public System.Collections.Generic.IReadOnlyDictionary<int, ET.Server.StartSceneConfig> DataMap => _dataMap;
    public ET.Server.StartSceneConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public ET.Server.StartSceneConfig Get(int key) => _dataMap[key];
    public ET.Server.StartSceneConfig this[int key] => _dataMap[key];

    public void ResolveRef()
    {
        foreach (var _v in _dataMap.Values)
        {
            _v.ResolveRef();
        }
        EndRef();
    }

    partial void EndRef();
}
}

