
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;
using MongoDB.Bson.Serialization.Attributes;
using MongoDB.Bson.Serialization.Options;
using SimpleJSON;

namespace ET.Server
{

    [ConfigProcess(ConfigType.Json)]
    public partial class StartProcessConfigCategory : Singleton<StartProcessConfigCategory>, IConfig
    {
        [BsonElement]
        [BsonDictionaryOptions(DictionaryRepresentation.ArrayOfArrays)]
        private readonly Dictionary<int, ET.Server.StartProcessConfig> _dataMap;
        private readonly List<ET.Server.StartProcessConfig> _dataList;

        public StartProcessConfigCategory(JSONNode _buf)
        {
            _dataMap = new Dictionary<int, ET.Server.StartProcessConfig>();
            _dataList = new List<ET.Server.StartProcessConfig>();

            foreach(JSONNode _ele in _buf.Children)
            {
                ET.Server.StartProcessConfig _v;
                { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::ET.Server.StartProcessConfig.DeserializeStartProcessConfig(_ele);  }
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }
            EndInit();
        }

        public Dictionary<int, ET.Server.StartProcessConfig> GetAll() => _dataMap;
        public Dictionary<int, ET.Server.StartProcessConfig> DataMap => _dataMap;
        public List<ET.Server.StartProcessConfig> DataList => _dataList;

        public ET.Server.StartProcessConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);

        public ET.Server.StartProcessConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            throw new System.Exception($"not found config: {this.GetType().FullName}, key: {key}");
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
            EndRef();
        }


        partial void EndRef();
    }

}

