
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class QuestObjectiveParams_KillMonster : ET.QuestObjectiveParams
    {
        public QuestObjectiveParams_KillMonster(ByteBuf _buf)  : base(_buf) 
        {
            MonsterId = _buf.ReadInt();
            Count = _buf.ReadInt();

            EndInit();
        }

        public static QuestObjectiveParams_KillMonster DeserializeQuestObjectiveParams_KillMonster(ByteBuf _buf)
        {
            return new ET.QuestObjectiveParams_KillMonster(_buf);
        }

        /// <summary>
        /// 击杀的怪物Id
        /// </summary>
        public readonly int MonsterId;
        /// <summary>
        /// 击杀数量
        /// </summary>
        public readonly int Count;
    
        public const int __ID__ = -933968487;
        public override int GetTypeId() => __ID__;

        public override void ResolveRef()
        {
            base.ResolveRef();
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "MonsterId:" + MonsterId + ","
            + "Count:" + Count + ","
            + "}";
        }

        partial void EndRef();
    }

}

