
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET.YIUITest
{

    [Config]
    public partial class YIUIClientConfigCategory : Singleton<YIUIClientConfigCategory>, ILubanConfig
    {
        private readonly Dictionary<int, YIUITest.YIUIClientConfig> _dataMap;
        private readonly List<YIUITest.YIUIClientConfig> _dataList;
        
        public YIUIClientConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, YIUITest.YIUIClientConfig>();
            _dataList = new List<YIUITest.YIUIClientConfig>();
            
            for(int n = _buf.ReadSize() ; n > 0 ; --n)
            {
                YIUITest.YIUIClientConfig _v;
                _v = YIUITest.YIUIClientConfig.DeserializeYIUIClientConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }
            EndInit();
        }

        public Dictionary<int, YIUITest.YIUIClientConfig> GetAll() => _dataMap;
        public Dictionary<int, YIUITest.YIUIClientConfig> DataMap => _dataMap;
        public List<YIUITest.YIUIClientConfig> DataList => _dataList;

        public YIUITest.YIUIClientConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);

        public YIUITest.YIUIClientConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            LubanLog.Error(this,key);
            return default;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
            EndRef();
        }


        partial void EndRef();
    }

}

