
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Luban;


namespace ET.Server
{
[ConfigGroup("Release")]
public sealed class StartProcessConfigCategoryFactory_Release : IConfigFactory
{
    public System.Type ConfigType => typeof(StartProcessConfigCategory);

    public ASingleton Create()
    {
        return new StartProcessConfigCategory(new System.Collections.Generic.Dictionary<int, ET.Server.StartProcessConfig>()
        {
            [ 1 ] = new ET.Server.StartProcessConfig(1, 1, 40001, 1, @"ServiceDiscovery"),
            [ 2 ] = new ET.Server.StartProcessConfig(2, 1, 0, 1, @"RouterManager"),
            [ 3 ] = new ET.Server.StartProcessConfig(3, 1, 0, 4, @"Router"),
            [ 14 ] = new ET.Server.StartProcessConfig(14, 1, 0, 1, @"Realm"),
            [ 15 ] = new ET.Server.StartProcessConfig(15, 1, 0, 2, @"Gate"),
            [ 25 ] = new ET.Server.StartProcessConfig(25, 1, 0, 1, @"Location"),
            [ 26 ] = new ET.Server.StartProcessConfig(26, 1, 0, 1, @"MapManager")
        });
    }
}
}
