
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Luban;


namespace ET
{
public partial class MapTransferRuleConfigCategory
{
    public MapTransferRuleConfigCategory()
    {
        _dataList = new System.Collections.Generic.List<ET.MapTransferRuleConfig>()
        {
            new ET.MapTransferRuleConfig(1, @"Map2", new float[] { }),
            new ET.MapTransferRuleConfig(2, @"Map1", new float[] { }),
            new ET.MapTransferRuleConfig(3, @"Lordaeron", new float[] { })
        };
        _dataMap = new System.Collections.Generic.Dictionary<int, ET.MapTransferRuleConfig>(_dataList.Count);
        foreach (var _v in _dataList)
        {
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }
}
}
