
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Luban;


namespace ET
{
public partial class TextConfigCategory
{
    public TextConfigCategory()
    {
        _dataList = new System.Collections.Generic.List<ET.TextConfig>()
        {
            new ET.TextConfig(38001, @"Quest_NotAvailable", @"任务无效", @""),
            new ET.TextConfig(38002, @"Quest_AlreadyAccepted", @"任务已接", @""),
            new ET.TextConfig(38003, @"Quest_ComponentNotFound", @"任务组件不存在", @""),
            new ET.TextConfig(38004, @"Quest_NotFound", @"任务没找到", @""),
            new ET.TextConfig(38005, @"Quest_NotFoundNPC", @"没有找到NPC", @""),
            new ET.TextConfig(38006, @"Quest_NPCTooFar", @"NPC太远了", @""),
            new ET.TextConfig(38007, @"Quest_NotFinish", @"任务没有完成", @""),
            new ET.TextConfig(37000, @"SpellCast_DistanceNotEnought", @"技能施放距离不够！", @"技能施放距离不够"),
            new ET.TextConfig(37001, @"SpellCast_NotSelectTarget", @"没有选择目标！", @""),
            new ET.TextConfig(37002, @"SpellCast_TargetTooFar", @"目标距离太远！", @""),
            new ET.TextConfig(37003, @"SpellCast_SpellInCD", @"技能在冷却中！", @""),
            new ET.TextConfig(37004, @"SpellCast_MPNotEnought", @"魔法值不足！", @""),
            new ET.TextConfig(37005, @"SpellCast_HPNotEnought", @"生命值不足！", @""),
            new ET.TextConfig(37006, @"SpellCast_TargetNotInFrontOfCaster", @"目标不在前方！", @"")
        };
        _dataMap = new System.Collections.Generic.Dictionary<int, ET.TextConfig>(_dataList.Count);
        foreach (var _v in _dataList)
        {
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }
}
}
