
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
[ConfigGroup("Config")]
public sealed class EquipmentConfigCategoryFactory_Config : IConfigFactory
{
    public System.Type ConfigType => typeof(EquipmentConfigCategory);

    public ASingleton Create()
    {
        return new EquipmentConfigCategory(new System.Collections.Generic.Dictionary<int, ET.EquipmentConfig>()
        {
            [ 10004 ] = new ET.EquipmentConfig(10004, 1),
            [ 10005 ] = new ET.EquipmentConfig(10005, 2),
            [ 10006 ] = new ET.EquipmentConfig(10006, 3),
            [ 10007 ] = new ET.EquipmentConfig(10007, 3),
            [ 10008 ] = new ET.EquipmentConfig(10008, 4),
            [ 10009 ] = new ET.EquipmentConfig(10009, 5),
            [ 10010 ] = new ET.EquipmentConfig(10010, 1),
            [ 10011 ] = new ET.EquipmentConfig(10011, 7),
            [ 10012 ] = new ET.EquipmentConfig(10012, 8)
        });
    }
}
}
