
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Luban;


namespace ET
{
[ConfigGroup("Config")]
public sealed class ItemConfigCategoryFactory_Config : IConfigFactory
{
    public System.Type ConfigType => typeof(ItemConfigCategory);

    public ASingleton Create()
    {
        return new ItemConfigCategory(new System.Collections.Generic.Dictionary<int, ET.ItemConfig>()
        {
            [ 10001 ] = new ET.ItemConfig(10001, @"生命药水", @"恢复100点生命值", 2, 99, @"Items/Potion_HP", 1, 1, 1),
            [ 10002 ] = new ET.ItemConfig(10002, @"魔法药水", @"恢复100点魔法值", 2, 99, @"Items/Potion_MP", 1, 1, 1),
            [ 10003 ] = new ET.ItemConfig(10003, @"铁矿石", @"锻造材料", 3, 999, @"Items/Ore_Iron", 0, 0, 1),
            [ 10004 ] = new ET.ItemConfig(10004, @"新手之剑", @"适合初学者使用的铁剑", 4, 1, @"Items/Equipment/Weapon_Sword_01", 0, 2, 1),
            [ 10005 ] = new ET.ItemConfig(10005, @"皮革头盔", @"简单的皮革头盔", 4, 1, @"Items/Equipment/Helmet_Leather_01", 0, 2, 1),
            [ 10006 ] = new ET.ItemConfig(10006, @"铁制胸甲", @"坚固的铁制护甲", 4, 1, @"Items/Equipment/Armor_Iron_01", 1, 2, 5),
            [ 10007 ] = new ET.ItemConfig(10007, @"布袍", @"法师的入门长袍", 4, 1, @"Items/Equipment/Robe_Cloth_01", 0, 2, 1),
            [ 10008 ] = new ET.ItemConfig(10008, @"皮革护腿", @"适合游侠的护腿", 4, 1, @"Items/Equipment/Pants_Leather_01", 0, 2, 3),
            [ 10009 ] = new ET.ItemConfig(10009, @"铁靴", @"厚重的战士之靴", 4, 1, @"Items/Equipment/Boots_Iron_01", 1, 2, 5),
            [ 10010 ] = new ET.ItemConfig(10010, @"精灵之弓", @"轻盈的远程武器", 4, 1, @"Items/Equipment/Weapon_Bow_01", 1, 2, 5),
            [ 10011 ] = new ET.ItemConfig(10011, @"魔法项链", @"增强魔法的项链", 4, 1, @"Items/Equipment/Necklace_Magic_01", 2, 2, 10),
            [ 10012 ] = new ET.ItemConfig(10012, @"力量戒指", @"增加力量的戒指", 4, 1, @"Items/Equipment/Ring_Strength_01", 1, 2, 8)
        });
    }
}
}
