
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Luban;


namespace ET
{
public sealed class MapUnitConfigCategoryFactory : IConfigFactory
{
    public System.Type ConfigType => typeof(MapUnitConfigCategory);

    public ASingleton Create()
    {
        return new MapUnitConfigCategory(new System.Collections.Generic.Dictionary<int, ET.MapUnitConfig>()
        {
            [ 10002 ] = new ET.MapUnitConfig(10002, 1002, @"Map1"),
            [ 10004 ] = new ET.MapUnitConfig(10004, 1003, @"Map1"),
            [ 10005 ] = new ET.MapUnitConfig(10005, 1003, @"Map1"),
            [ 10006 ] = new ET.MapUnitConfig(10006, 1003, @"Map1"),
            [ 10007 ] = new ET.MapUnitConfig(10007, 1003, @"Map1"),
            [ 10008 ] = new ET.MapUnitConfig(10008, 1003, @"Map1"),
            [ 10009 ] = new ET.MapUnitConfig(10009, 1004, @"Map1"),
            [ 10010 ] = new ET.MapUnitConfig(10010, 1004, @"Map1"),
            [ 10011 ] = new ET.MapUnitConfig(10011, 1004, @"Map1"),
            [ 10012 ] = new ET.MapUnitConfig(10012, 1004, @"Map1"),
            [ 10013 ] = new ET.MapUnitConfig(10013, 1004, @"Map1"),
            [ 10014 ] = new ET.MapUnitConfig(10014, 1003, @"Map2"),
            [ 10015 ] = new ET.MapUnitConfig(10015, 1003, @"Map2"),
            [ 10016 ] = new ET.MapUnitConfig(10016, 1003, @"Map2"),
            [ 10017 ] = new ET.MapUnitConfig(10017, 1003, @"Map2"),
            [ 10018 ] = new ET.MapUnitConfig(10018, 1003, @"Map2"),
            [ 10019 ] = new ET.MapUnitConfig(10019, 1004, @"Map2"),
            [ 10020 ] = new ET.MapUnitConfig(10020, 1004, @"Map2"),
            [ 10021 ] = new ET.MapUnitConfig(10021, 1004, @"Map2"),
            [ 10022 ] = new ET.MapUnitConfig(10022, 1004, @"Map2"),
            [ 10023 ] = new ET.MapUnitConfig(10023, 1004, @"Map2"),
            [ 10024 ] = new ET.MapUnitConfig(10024, 1005, @"Map2"),
            [ 10025 ] = new ET.MapUnitConfig(10025, 1005, @"Map2"),
            [ 10026 ] = new ET.MapUnitConfig(10026, 1002, @"Map2")
        });
    }
}
}
