
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class StartZoneConfig : Luban.BeanBase
    {
        public StartZoneConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            ZoneType = _buf.ReadInt();
            DBConnection = _buf.ReadString();
            DBName = _buf.ReadString();

            EndInit();
        }

        public static StartZoneConfig DeserializeStartZoneConfig(ByteBuf _buf)
        {
            return new StartZoneConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// ZoneType
        /// </summary>
        public readonly int ZoneType;
        /// <summary>
        /// 数据库地址
        /// </summary>
        public readonly string DBConnection;
        /// <summary>
        /// 数据库名
        /// </summary>
        public readonly string DBName;
    
        public const int __ID__ = -457316368;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "ZoneType:" + ZoneType + ","
            + "DBConnection:" + DBConnection + ","
            + "DBName:" + DBName + ","
            + "}";
        }

        partial void EndRef();
    }

}

