
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET.YIUITest
{
    /// <summary>
    /// 这是一个矩形
    /// </summary>
    [EnableClass]
    public sealed partial class YIUIRectangle : YIUIShape
    {
        public YIUIRectangle(ByteBuf _buf)  : base(_buf) 
        {
            Width = _buf.ReadFloat();
            Height = _buf.ReadFloat();

            EndInit();
        }

        public static YIUIRectangle DeserializeYIUIRectangle(ByteBuf _buf)
        {
            return new YIUITest.YIUIRectangle(_buf);
        }

        /// <summary>
        /// 宽度
        /// </summary>
        public readonly float Width;
        /// <summary>
        /// 高度
        /// </summary>
        public readonly float Height;
    
        public const int __ID__ = -813983597;
        public override int GetTypeId() => __ID__;

        public override void ResolveRef()
        {
            base.ResolveRef();
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "width:" + Width + ","
            + "height:" + Height + ","
            + "}";
        }

        partial void EndRef();
    }

}

