
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET.YIUITest
{
    [EnableClass]
    public sealed partial class YIUIItemConfig : Luban.BeanBase
    {
        public YIUIItemConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            Price = _buf.ReadInt();
            UpgradeToItemId = _buf.ReadInt();
            UpgradeToItemId_Ref = null;
            if(_buf.ReadBool()){ ExpireTime = _buf.ReadLong(); } else { ExpireTime = null; }
            Quality = (YIUITest.EYIUIQuality)_buf.ReadInt();
            {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);ExchangeList = new System.Collections.Generic.List<YIUITest.YIUIItemExchange>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { YIUITest.YIUIItemExchange _e0;  _e0 = YIUITest.YIUIItemExchange.DeserializeYIUIItemExchange(_buf); ExchangeList.Add(_e0);}}
            ExchangeColumn = YIUITest.YIUIItemExchange.DeserializeYIUIItemExchange(_buf);

            EndInit();
        }

        public static YIUIItemConfig DeserializeYIUIItemConfig(ByteBuf _buf)
        {
            return new YIUITest.YIUIItemConfig(_buf);
        }

        /// <summary>
        /// 这是id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 名字
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// 价格
        /// </summary>
        public readonly int Price;
        /// <summary>
        /// 引用当前表
        /// </summary>
        public readonly int UpgradeToItemId;
        public YIUITest.YIUIItemConfig UpgradeToItemId_Ref;
        /// <summary>
        /// 过期时间
        /// </summary>
        public readonly long? ExpireTime;
        /// <summary>
        /// 品质
        /// </summary>
        public readonly YIUITest.EYIUIQuality Quality;
        public readonly System.Collections.Generic.List<YIUITest.YIUIItemExchange> ExchangeList;
        /// <summary>
        /// 道具兑换配置
        /// </summary>
        public readonly YIUITest.YIUIItemExchange ExchangeColumn;
    
        public const int __ID__ = 1673234833;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            UpgradeToItemId_Ref = YIUIItemConfigCategory.Instance.GetOrDefault(UpgradeToItemId);
            foreach (var _e in ExchangeList) { _e?.ResolveRef(); }
            ExchangeColumn?.ResolveRef();
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "id:" + Id + ","
            + "name:" + Name + ","
            + "price:" + Price + ","
            + "upgradeToItemId:" + UpgradeToItemId + ","
            + "expireTime:" + ExpireTime + ","
            + "quality:" + Quality + ","
            + "exchangeList:" + Luban.StringUtil.CollectionToString(ExchangeList) + ","
            + "exchangeColumn:" + ExchangeColumn + ","
            + "}";
        }

        partial void EndRef();
    }

}

