
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET.YIUITest
{
    [EnableClass]
    public abstract partial class YIUIShape : Luban.BeanBase
    {
        public YIUIShape(ByteBuf _buf) 
        {

            EndInit();
        }

        public static YIUIShape DeserializeYIUIShape(ByteBuf _buf)
        {
            switch (_buf.ReadInt())
            {
                case YIUITest.YIUICircle.__ID__: return new YIUITest.YIUICircle(_buf);
                case YIUITest.YIUIRectangle.__ID__: return new YIUITest.YIUIRectangle(_buf);
                default: throw new SerializationException();
            }
        }

    

        public virtual void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "}";
        }

        partial void EndRef();
    }

}

