
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class TextConfig : Luban.BeanBase
    {
        public TextConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            CN = _buf.ReadString();
            EN = _buf.ReadString();

            EndInit();
        }

        public static TextConfig DeserializeTextConfig(ByteBuf _buf)
        {
            return new TextConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 名字
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// 中文
        /// </summary>
        public readonly string CN;
        /// <summary>
        /// 英文
        /// </summary>
        public readonly string EN;
    
        public const int __ID__ = -912442641;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "CN:" + CN + ","
            + "EN:" + EN + ","
            + "}";
        }

        partial void EndRef();
    }

}

