
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET.Server
{
[ConfigGroup("Moba")]
public sealed class StartProcessConfigCategoryFactory_Moba : IConfigFactory
{
    public System.Type ConfigType => typeof(StartProcessConfigCategory);

    public ASingleton Create()
    {
        return new StartProcessConfigCategory(new System.Collections.Generic.Dictionary<int, ET.Server.StartProcessConfig>()
        {
            [ 1 ] = new ET.Server.StartProcessConfig(1, 1, 40001, 1, @"ServiceDiscovery"),
            [ 2 ] = new ET.Server.StartProcessConfig(2, 1, 0, 1, @"RouterManager"),
            [ 3 ] = new ET.Server.StartProcessConfig(3, 1, 0, 4, @"Router"),
            [ 1003 ] = new ET.Server.StartProcessConfig(1003, 1, 0, 1, @"Realm"),
            [ 1004 ] = new ET.Server.StartProcessConfig(1004, 1, 0, 2, @"Gate"),
            [ 2004 ] = new ET.Server.StartProcessConfig(2004, 1, 0, 1, @"Location"),
            [ 2005 ] = new ET.Server.StartProcessConfig(2005, 1, 0, 2, @"Match"),
            [ 3005 ] = new ET.Server.StartProcessConfig(3005, 1, 0, 2, @"MapManager")
        });
    }
}
}
