
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class MapTransferRuleConfig : Luban.BeanBase
    {
        public MapTransferRuleConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            ToMap = _buf.ReadString();
            {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Pos = new float[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { float __e0;__e0 = _buf.ReadFloat(); Pos[__index0] = __e0;}}

            EndInit();
        }

        public static MapTransferRuleConfig DeserializeMapTransferRuleConfig(ByteBuf _buf)
        {
            return new ET.MapTransferRuleConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 目标地图
        /// </summary>
        public readonly string ToMap;
        /// <summary>
        /// 目标位置
        /// </summary>
        public readonly float[] Pos;
    
        public const int __ID__ = 2092018182;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "ToMap:" + ToMap + ","
            + "Pos:" + Luban.StringUtil.CollectionToString(Pos) + ","
            + "}";
        }

        partial void EndRef();
    }

}

