
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class MapUnitConfig : Luban.BeanBase
    {
        public MapUnitConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            UnitConfigId = _buf.ReadInt();
            MapName = _buf.ReadString();

            EndInit();
        }

        public static MapUnitConfig DeserializeMapUnitConfig(ByteBuf _buf)
        {
            return new ET.MapUnitConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// UnitConfigId
        /// </summary>
        public readonly int UnitConfigId;
        /// <summary>
        /// 所在地图
        /// </summary>
        public readonly string MapName;
    
        public const int __ID__ = -2012370621;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "UnitConfigId:" + UnitConfigId + ","
            + "MapName:" + MapName + ","
            + "}";
        }

        partial void EndRef();
    }

}

