
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class QuestObjectiveParams_Collectltem : ET.QuestObjectiveParams
    {
        public QuestObjectiveParams_Collectltem(ByteBuf _buf)  : base(_buf) 
        {
            ItemId = _buf.ReadInt();
            Count = _buf.ReadInt();

            EndInit();
        }

        public static QuestObjectiveParams_Collectltem DeserializeQuestObjectiveParams_Collectltem(ByteBuf _buf)
        {
            return new ET.QuestObjectiveParams_Collectltem(_buf);
        }

        /// <summary>
        /// 道具Id
        /// </summary>
        public readonly int ItemId;
        /// <summary>
        /// 道具数量
        /// </summary>
        public readonly int Count;
    
        public const int __ID__ = -1135305897;
        public override int GetTypeId() => __ID__;

        public override void ResolveRef()
        {
            base.ResolveRef();
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "ItemId:" + ItemId + ","
            + "Count:" + Count + ","
            + "}";
        }

        partial void EndRef();
    }

}

