
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class UnitConfig : Luban.BeanBase
    {
        public UnitConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            UnitType = (ET.UnitType)_buf.ReadInt();
            Name = _buf.ReadString();
            MapName = _buf.ReadString();
            HeadIcon = _buf.ReadString();
            ClassType = (ET.EClassType)_buf.ReadInt();

            EndInit();
        }

        public static UnitConfig DeserializeUnitConfig(ByteBuf _buf)
        {
            return new ET.UnitConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// Type
        /// </summary>
        public readonly ET.UnitType UnitType;
        /// <summary>
        /// 名字
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// 所在地图
        /// </summary>
        public readonly string MapName;
        /// <summary>
        /// 头像图片
        /// </summary>
        public readonly string HeadIcon;
        /// <summary>
        /// 职业
        /// </summary>
        public readonly ET.EClassType ClassType;
    
        public const int __ID__ = 1859130533;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "UnitType:" + UnitType + ","
            + "Name:" + Name + ","
            + "MapName:" + MapName + ","
            + "headIcon:" + HeadIcon + ","
            + "classType:" + ClassType + ","
            + "}";
        }

        partial void EndRef();
    }

}

