
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Luban;


namespace ET.Server
{
[ConfigGroup("Localhost")]
public sealed class StartMachineConfigCategoryFactory_Localhost : IConfigFactory
{
    public System.Type ConfigType => typeof(StartMachineConfigCategory);

    public ASingleton Create()
    {
        return new StartMachineConfigCategory(new System.Collections.Generic.Dictionary<int, ET.Server.StartMachineConfig>()
        {
            [ 1 ] = new ET.Server.StartMachineConfig(1, @"127.0.0.1", @"127.0.0.1")
        });
    }
}
}
