
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Luban;


namespace ET.Server
{
[ConfigGroup("Localhost")]
public sealed class StartSceneConfigCategoryFactory_Localhost : IConfigFactory
{
    public System.Type ConfigType => typeof(StartSceneConfigCategory);

    public ASingleton Create()
    {
        return new StartSceneConfigCategory(new System.Collections.Generic.Dictionary<int, ET.Server.StartSceneConfig>()
        {
            [ 1 ] = new ET.Server.StartSceneConfig(1, 1, 0, @"ServiceDiscovery", @"ServiceDiscovery", 0),
            [ 2 ] = new ET.Server.StartSceneConfig(2, 1, 0, @"Location", @"Location", 0),
            [ 3 ] = new ET.Server.StartSceneConfig(3, 1, 0, @"RouterManager", @"RouterManager", 10101),
            [ 4 ] = new ET.Server.StartSceneConfig(4, 1, 0, @"Router", @"Router01", 0),
            [ 5 ] = new ET.Server.StartSceneConfig(5, 1, 0, @"Router", @"Router02", 0),
            [ 6 ] = new ET.Server.StartSceneConfig(6, 1, 0, @"Router", @"Router03", 0),
            [ 7 ] = new ET.Server.StartSceneConfig(7, 1, 0, @"Router", @"Router04", 0),
            [ 8 ] = new ET.Server.StartSceneConfig(8, 1, 0, @"Realm", @"Realm", 0),
            [ 9 ] = new ET.Server.StartSceneConfig(9, 1, 0, @"Gate", @"Gate1", 0),
            [ 10 ] = new ET.Server.StartSceneConfig(10, 1, 0, @"Gate", @"Gate2", 0),
            [ 11 ] = new ET.Server.StartSceneConfig(11, 1, 0, @"MapManager", @"MapManager", 0)
        });
    }
}
}
