using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace ET.Client
{
    public static class BTConfigCodeExporter
    {
        private const string DefaultConfigGroup = ConfigGroupNames.Config;
        private const string AutoGeneratedHeader =
@"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------";

        private static readonly string[] HotfixConfigDirs =
        {
            "Packages/cn.etetet.spell/CodeMode/Config/Client/Config",
            "Packages/cn.etetet.spell/CodeMode/Config/ClientServer/Config",
            "Packages/cn.etetet.spell/CodeMode/Config/Server/Config",
        };

        public static void Export(SpellConfigCategory spellConfigCategory, BuffConfigCategory buffConfigCategory)
        {
            string spellFactoryCode = GenerateFactoryCode(
                $"SpellConfigCategoryFactory_{DefaultConfigGroup}",
                "SpellConfigCategory",
                spellConfigCategory.GetAll().Values.OrderBy(x => x.Id).ToList());

            string buffFactoryCode = GenerateFactoryCode(
                $"BuffConfigCategoryFactory_{DefaultConfigGroup}",
                "BuffConfigCategory",
                buffConfigCategory.GetAll().Values.OrderBy(x => x.Id).ToList());

            foreach (string outputDir in HotfixConfigDirs)
            {
                Directory.CreateDirectory(outputDir);

                WriteAllTextIfChanged(Path.Combine(outputDir, $"SpellConfigCategoryFactory_{DefaultConfigGroup}.cs"), spellFactoryCode);
                WriteAllTextIfChanged(Path.Combine(outputDir, $"BuffConfigCategoryFactory_{DefaultConfigGroup}.cs"), buffFactoryCode);
            }

            AssetDatabase.Refresh();
        }

        private static string GenerateFactoryCode<TConfig>(string factoryTypeName, string categoryTypeName, List<TConfig> items)
        {
            CSharpObjectCodeEmitter emitter = new();
            CodeWriter writer = new();
            string configTypeName = $"global::{typeof(TConfig).FullName}";
            writer.AppendLine(AutoGeneratedHeader.TrimEnd());
            writer.AppendLine("namespace ET");
            writer.AppendLine("{");
            using (writer.PushIndent())
            {
                writer.AppendLine($"[ConfigGroup(\"{DefaultConfigGroup}\")]");
                writer.AppendLine($"public sealed class {factoryTypeName} : IConfigFactory");
                writer.AppendLine("{");
                using (writer.PushIndent())
                {
                    writer.AppendLine($"public System.Type ConfigType => typeof(global::ET.{categoryTypeName});");
                    writer.AppendLine();
                    writer.AppendLine("public ASingleton Create()");
                    writer.AppendLine("{");
                    using (writer.PushIndent())
                    {
                        writer.AppendLine($"return new global::ET.{categoryTypeName}(new global::System.Collections.Generic.Dictionary<int, {configTypeName}>()");
                        writer.AppendLine("{");
                        using (writer.PushIndent())
                        {
                            foreach (TConfig item in items)
                            {
                                writer.AppendMultiline($"[ {GetConfigId(item)} ] = {emitter.Emit(item)},");
                            }
                        }
                        writer.AppendLine("});");
                    }
                    writer.AppendLine("}");
                }
                writer.AppendLine("}");
            }
            writer.AppendLine("}");
            return writer.ToString();
        }

        private static int GetConfigId<TConfig>(TConfig item)
        {
            const BindingFlags flags = BindingFlags.Instance | BindingFlags.Public;
            Type type = item.GetType();

            if (type.GetField("Id", flags) is { FieldType: var fieldType } field && fieldType == typeof(int))
            {
                return (int)field.GetValue(item);
            }

            if (type.GetProperty("Id", flags) is { PropertyType: var propertyType } property && propertyType == typeof(int))
            {
                return (int)property.GetValue(item);
            }

            throw new InvalidOperationException($"{type.FullName} 缺少 public int Id，无法生成配置字典 Factory。");
        }

        private static void WriteAllTextIfChanged(string path, string content)
        {
            if (File.Exists(path))
            {
                string existing = File.ReadAllText(path);
                if (string.Equals(existing, content, StringComparison.Ordinal))
                {
                    return;
                }
            }

            File.WriteAllText(path, content, new UTF8Encoding(false));
            Debug.Log($"Generated config factory: {path}");
        }

        private sealed class CodeWriter
        {
            private readonly StringBuilder sb = new();
            private int indent;

            public IDisposable PushIndent()
            {
                this.indent++;
                return new IndentScope(this);
            }

            public void AppendLine(string line = "")
            {
                if (line.Length == 0)
                {
                    this.sb.AppendLine();
                    return;
                }

                this.sb.Append(' ', this.indent * 4);
                this.sb.AppendLine(line);
            }

            public void AppendMultiline(string text)
            {
                string[] lines = text.Replace("\r\n", "\n").Split('\n');
                foreach (string line in lines)
                {
                    this.AppendLine(line);
                }
            }

            public override string ToString()
            {
                return this.sb.ToString();
            }

            private sealed class IndentScope : IDisposable
            {
                private readonly CodeWriter context;

                public IndentScope(CodeWriter context)
                {
                    this.context = context;
                }

                public void Dispose()
                {
                    this.context.indent--;
                }
            }
        }

    }
}
