
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Luban;


namespace ET
{
public partial class ItemConfigCategory
{
    public ItemConfigCategory()
    {
        _dataList = new System.Collections.Generic.List<ET.ItemConfig>()
        {
            new ET.ItemConfig(10001, @"生命药水", 2, 99, 1, 1, 1),
            new ET.ItemConfig(10002, @"魔法药水", 2, 99, 1, 1, 1),
            new ET.ItemConfig(10003, @"铁矿石", 3, 999, 0, 0, 1),
            new ET.ItemConfig(10004, @"新手之剑", 4, 1, 0, 2, 1),
            new ET.ItemConfig(10005, @"皮革头盔", 4, 1, 0, 2, 1),
            new ET.ItemConfig(10006, @"铁制胸甲", 4, 1, 1, 2, 5),
            new ET.ItemConfig(10007, @"布袍", 4, 1, 0, 2, 1),
            new ET.ItemConfig(10008, @"皮革护腿", 4, 1, 0, 2, 3),
            new ET.ItemConfig(10009, @"铁靴", 4, 1, 1, 2, 5),
            new ET.ItemConfig(10010, @"精灵之弓", 4, 1, 1, 2, 5),
            new ET.ItemConfig(10011, @"魔法项链", 4, 1, 2, 2, 10),
            new ET.ItemConfig(10012, @"力量戒指", 4, 1, 1, 2, 8)
        };
        _dataMap = new System.Collections.Generic.Dictionary<int, ET.ItemConfig>(_dataList.Count);
        foreach (var _v in _dataList)
        {
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }
}
}
