
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Luban;


namespace ET
{
public sealed class MapTransferRuleConfigCategoryFactory : IConfigFactory
{
    public System.Type ConfigType => typeof(MapTransferRuleConfigCategory);

    public ASingleton Create()
    {
        return new MapTransferRuleConfigCategory(new System.Collections.Generic.List<ET.MapTransferRuleConfig>()
        {
            new ET.MapTransferRuleConfig(1, @"Map2", new float[] { }),
            new ET.MapTransferRuleConfig(2, @"Map1", new float[] { }),
            new ET.MapTransferRuleConfig(3, @"Lordaeron", new float[] { })
        });
    }
}
}
