
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Luban;


namespace ET
{
public partial class QuestObjectiveConfigCategory
{
    public QuestObjectiveConfigCategory()
    {
        _dataList = new System.Collections.Generic.List<ET.QuestObjectiveConfig>()
        {
            new ET.QuestObjectiveConfig(1, @"击杀3只野猪", @"击杀3只野猪", ET.QuestObjectiveType.KillMonster, 3, new ET.QuestObjectiveParams_KillMonster(1003)),
            new ET.QuestObjectiveConfig(2, @"击杀1头熊", @"击杀1头熊", ET.QuestObjectiveType.KillMonster, 1, new ET.QuestObjectiveParams_KillMonster(1004))
        };
        _dataMap = new System.Collections.Generic.Dictionary<int, ET.QuestObjectiveConfig>(_dataList.Count);
        foreach (var _v in _dataList)
        {
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }
}
}
