
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{ 
    public enum CopyType
    {
        /// <summary>
        /// 普通地图
        /// </summary>
        Normal = 1,
        /// <summary>
        /// 分线
        /// </summary>
        Line = 2,
        /// <summary>
        /// 副本
        /// </summary>
        Copy = 3,
    }

} 

