
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Luban;


namespace ET.Server
{
[ConfigGroup("Localhost")]
public sealed class StartProcessConfigCategoryFactory_Localhost : IConfigFactory
{
    public System.Type ConfigType => typeof(StartProcessConfigCategory);

    public ASingleton Create()
    {
        return new StartProcessConfigCategory(new System.Collections.Generic.Dictionary<int, ET.Server.StartProcessConfig>()
        {
            [ 1 ] = new ET.Server.StartProcessConfig(1, 1, 40001, 0, @"Localhost")
        });
    }
}
}
