
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ET.Server
{
    public sealed partial class StartZoneConfig : ET.Object
    {
        public StartZoneConfig(int Id, int ZoneType, string DBConnection, string DBName) 
        {
            this.Id = Id;
            this.ZoneType = ZoneType;
            this.DBConnection = DBConnection;
            this.DBName = DBName;
            EndInit();
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// ZoneType
        /// </summary>
        public readonly int ZoneType;
        /// <summary>
        /// 数据库地址
        /// </summary>
        public readonly string DBConnection;
        /// <summary>
        /// 数据库名
        /// </summary>
        public readonly string DBName;

        public  void ResolveRef()
        {
            EndRef();
        }

        partial void EndInit();
        partial void EndRef();
    }

}

