
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET.Server
{
[ConfigProcess(ConfigType.Code)]
public partial class StartMachineConfigCategory : Singleton<StartMachineConfigCategory>, IConfig
{
    private readonly System.Collections.Generic.Dictionary<int, ET.Server.StartMachineConfig> _dataMap;

    public StartMachineConfigCategory(System.Collections.Generic.Dictionary<int, ET.Server.StartMachineConfig> dataMap)
    {
        _dataMap = dataMap;
        EndInit();
    }

    public System.Collections.Generic.Dictionary<int, ET.Server.StartMachineConfig> GetAll() => _dataMap;
    public System.Collections.Generic.IReadOnlyDictionary<int, ET.Server.StartMachineConfig> DataMap => _dataMap;
    public ET.Server.StartMachineConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public ET.Server.StartMachineConfig Get(int key) => _dataMap[key];
    public ET.Server.StartMachineConfig this[int key] => _dataMap[key];

    public void ResolveRef()
    {
        foreach (var _v in _dataMap.Values)
        {
            _v.ResolveRef();
        }
        EndRef();
    }

    partial void EndRef();
}
}

