
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ET.Server
{
[ConfigProcess(ConfigType.Code)]
public partial class StartProcessConfigCategory : Singleton<StartProcessConfigCategory>, IConfig
{
    private readonly System.Collections.Generic.Dictionary<int, ET.Server.StartProcessConfig> _dataMap;

    public StartProcessConfigCategory(System.Collections.Generic.Dictionary<int, ET.Server.StartProcessConfig> dataMap)
    {
        _dataMap = dataMap;
    }

    public System.Collections.Generic.Dictionary<int, ET.Server.StartProcessConfig> GetAll() => _dataMap;
    public System.Collections.Generic.IReadOnlyDictionary<int, ET.Server.StartProcessConfig> DataMap => _dataMap;
    public ET.Server.StartProcessConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public ET.Server.StartProcessConfig Get(int key) => _dataMap[key];
    public ET.Server.StartProcessConfig this[int key] => _dataMap[key];

    public void ResolveRef()
    {
        foreach (var _v in _dataMap.Values)
        {
            _v.ResolveRef();
        }
        EndRef();
    }

    partial void EndRef();
}
}

