
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ET.Server
{
    [EnableClass]
    public sealed partial class StartZoneConfig : Luban.BeanBase
    {
        public StartZoneConfig(JSONNode _buf) 
        {
            { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
            { if(!_buf["ZoneType"].IsNumber) { throw new SerializationException(); }  ZoneType = _buf["ZoneType"]; }
            { if(!_buf["DBConnection"].IsString) { throw new SerializationException(); }  DBConnection = _buf["DBConnection"]; }
            { if(!_buf["DBName"].IsString) { throw new SerializationException(); }  DBName = _buf["DBName"]; }

            EndInit();
        }

        public static StartZoneConfig DeserializeStartZoneConfig(JSONNode _buf)
        {
            return new ET.Server.StartZoneConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// ZoneType
        /// </summary>
        public readonly int ZoneType;
        /// <summary>
        /// 数据库地址
        /// </summary>
        public readonly string DBConnection;
        /// <summary>
        /// 数据库名
        /// </summary>
        public readonly string DBName;

        public const int __ID__ = 350676868;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "ZoneType:" + ZoneType + ","
            + "DBConnection:" + DBConnection + ","
            + "DBName:" + DBName + ","
            + "}";
        }

        partial void EndRef();
    }

}

