
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ET.Server
{
    [EnableClass]
    public sealed partial class StartProcessConfig : Luban.BeanBase
    {
        public StartProcessConfig(JSONNode _buf) 
        {
            { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
            { if(!_buf["MachineId"].IsNumber) { throw new SerializationException(); }  MachineId = _buf["MachineId"]; }
            { if(!_buf["Port"].IsNumber) { throw new SerializationException(); }  Port = _buf["Port"]; }
            { if(!_buf["Num"].IsNumber) { throw new SerializationException(); }  Num = _buf["Num"]; }
            { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }

            EndInit();
        }

        public static StartProcessConfig DeserializeStartProcessConfig(JSONNode _buf)
        {
            return new ET.Server.StartProcessConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 所属机器
        /// </summary>
        public readonly int MachineId;
        /// <summary>
        /// 内网端口
        /// </summary>
        public readonly int Port;
        /// <summary>
        /// 数量
        /// </summary>
        public readonly int Num;
        /// <summary>
        /// 名字
        /// </summary>
        public readonly string Name;

        public const int __ID__ = -224756389;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "MachineId:" + MachineId + ","
            + "Port:" + Port + ","
            + "Num:" + Num + ","
            + "Name:" + Name + ","
            + "}";
        }

        partial void EndRef();
    }

}

